#include "agentsync.h"

#include <dirent.h>
#include <errno.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#include "text.h"
#include "vendor/cJSON.h"

static const char *const BACKENDS[] = {"claude", "codex", "pi"};

static const char *const CODEX_EVENTS[] = {
    "SessionStart", "UserPromptSubmit", "PreToolUse", "PostToolUse",
    "PermissionRequest", "Stop", "SessionEnd",
};

static const char *const OTHER_SKILL_DIRS[] = {
    ".codex/skills", ".pi/agent/skills", ".grok/skills",
};

static const char PI_EXTENSION[] =
    "// Generated by `mux sync`. Runs the hooks in ~/.config/mux/hooks.json\n"
    "// (Claude hook schema) from pi's extension events. Edit that file, not this.\n"
    "// Context a hook returns (raw stdout on SessionStart, or additionalContext in\n"
    "// hookSpecificOutput JSON) is appended to the system prompt each turn.\n"
    "import * as fs from \"node:fs\";\n"
    "import * as os from \"node:os\";\n"
    "import * as path from \"node:path\";\n"
    "import { spawn } from \"node:child_process\";\n"
    "\n"
    "type Handler = { command: string; timeout?: number };\n"
    "type Group = { matcher?: RegExp; hooks: Handler[] };\n"
    "\n"
    "function load(): Record<string, Group[]> {\n"
    "  const out: Record<string, Group[]> = {};\n"
    "  try {\n"
    "    const file = path.join(os.homedir(), \".config\", \"mux\", \"hooks.json\");\n"
    "    const hooks = JSON.parse(fs.readFileSync(file, \"utf8\")).hooks || {};\n"
    "    for (const [event, groups] of Object.entries<any>(hooks)) {\n"
    "      out[event] = [];\n"
    "      for (const g of groups || []) {\n"
    "        const hs: Handler[] = [];\n"
    "        for (const h of g.hooks || []) {\n"
    "          if (h.type && h.type !== \"command\") continue;\n"
    "          if (h.pi === false) continue;\n"
    "          const command = typeof h.pi === \"string\" ? h.pi : h.command;\n"
    "          if (command) hs.push({ command, timeout: h.timeout });\n"
    "        }\n"
    "        if (hs.length)\n"
    "          out[event].push({ matcher: g.matcher ? new RegExp(g.matcher) : undefined, hooks: hs });\n"
    "      }\n"
    "    }\n"
    "  } catch {}\n"
    "  return out;\n"
    "}\n"
    "\n"
    "const HOOKS = load();\n"
    "let sessionContext = \"\";\n"
    "\n"
    "function sessionId(ctx: any): string {\n"
    "  try {\n"
    "    const id = ctx && ctx.sessionManager && ctx.sessionManager.getSessionId();\n"
    "    if (id) return String(id);\n"
    "  } catch {}\n"
    "  return `pi-${process.pid}`;\n"
    "}\n"
    "\n"
    "function context(stdout: string): string {\n"
    "  const text = stdout.trim();\n"
    "  if (!text) return \"\";\n"
    "  if (text[0] !== \"{\") return text;\n"
    "  try {\n"
    "    const o = JSON.parse(text);\n"
    "    return String((o.hookSpecificOutput && o.hookSpecificOutput.additionalContext) ||\n"
    "                  o.additionalContext || o.additional_context || \"\");\n"
    "  } catch {\n"
    "    return text;\n"
    "  }\n"
    "}\n"
    "\n"
    "function exec(h: Handler, payload: string): Promise<string> {\n"
    "  return new Promise((resolve) => {\n"
    "    let out = \"\";\n"
    "    try {\n"
    "      const child = spawn(\"/bin/sh\", [\"-c\", h.command], {\n"
    "        stdio: [\"pipe\", \"pipe\", \"ignore\"],\n"
    "        env: { ...process.env, MUX_BACKEND: \"pi\" },\n"
    "      });\n"
    "      const timer = setTimeout(() => child.kill(), (h.timeout || 60) * 1000);\n"
    "      child.stdout.on(\"data\", (d) => { out += d; });\n"
    "      child.on(\"exit\", () => { clearTimeout(timer); resolve(context(out)); });\n"
    "      child.on(\"error\", () => { clearTimeout(timer); resolve(\"\"); });\n"
    "      child.stdin.on(\"error\", () => {});\n"
    "      child.stdin.end(payload);\n"
    "    } catch {\n"
    "      resolve(\"\");\n"
    "    }\n"
    "  });\n"
    "}\n"
    "\n"
    "async function run(event: string, subject: string, ctx: any, extra: Record<string, unknown>): Promise<string> {\n"
    "  const payload = JSON.stringify({\n"
    "    hook_event_name: event,\n"
    "    session_id: sessionId(ctx),\n"
    "    cwd: (ctx && ctx.cwd) || process.cwd(),\n"
    "    backend: \"pi\",\n"
    "    ...extra,\n"
    "  });\n"
    "  const jobs: Promise<string>[] = [];\n"
    "  for (const g of HOOKS[event] || []) {\n"
    "    if (g.matcher && !g.matcher.test(subject)) continue;\n"
    "    for (const h of g.hooks) jobs.push(exec(h, payload));\n"
    "  }\n"
    "  return (await Promise.all(jobs)).filter(Boolean).join(\"\\n\\n\");\n"
    "}\n"
    "\n"
    "export default function (pi: any) {\n"
    "  pi.on(\"session_start\", async (event: any, ctx: any) => {\n"
    "    const source = event?.reason || \"startup\";\n"
    "    sessionContext = await run(\"SessionStart\", source, ctx, { source });\n"
    "  });\n"
    "  pi.on(\"before_agent_start\", async (event: any, ctx: any) => {\n"
    "    const turn = await run(\"UserPromptSubmit\", \"\", ctx, { prompt: event?.prompt || \"\" });\n"
    "    const add = [sessionContext, turn].filter(Boolean).join(\"\\n\\n\");\n"
    "    if (!add) return;\n"
    "    return { systemPrompt: `${event?.systemPrompt || \"\"}\\n\\n${add}` };\n"
    "  });\n"
    "  pi.on(\"tool_call\", (event: any, ctx: any) =>\n"
    "    run(\"PreToolUse\", event?.toolName || \"\", ctx,\n"
    "        { tool_name: event?.toolName, tool_input: event?.input }).then(() => undefined));\n"
    "  pi.on(\"tool_result\", (event: any, ctx: any) =>\n"
    "    run(\"PostToolUse\", event?.toolName || \"\", ctx,\n"
    "        { tool_name: event?.toolName, tool_input: event?.input, is_error: !!event?.isError })\n"
    "      .then(() => undefined));\n"
    "  pi.on(\"agent_end\", (_event: any, ctx: any) => run(\"Stop\", \"\", ctx, {}).then(() => undefined));\n"
    "  pi.on(\"session_shutdown\", (_event: any, ctx: any) =>\n"
    "    run(\"SessionEnd\", \"exit\", ctx, { reason: \"exit\" }).then(() => undefined));\n"
    "}\n";

static int mkdir_p(const char *dir)
{
    char buf[PATH_MAX];
    if ((size_t)snprintf(buf, sizeof buf, "%s", dir) >= sizeof buf)
        return 0;
    for (char *p = buf + 1; *p; p++) {
        if (*p != '/')
            continue;
        *p = '\0';
        if (mkdir(buf, 0700) != 0 && errno != EEXIST)
            return 0;
        *p = '/';
    }
    return mkdir(buf, 0700) == 0 || errno == EEXIST;
}

static int at(char *out, size_t size, const char *home, const char *rel)
{
    return (size_t)snprintf(out, size, "%s/%s", home, rel) < size;
}

static int write_text(FILE *f, void *ud)
{
    return fputs((const char *)ud, f) >= 0;
}

static int same_text(const char *path, const char *text)
{
    char *have = text_slurp(path, 1u << 20, NULL);
    if (!have)
        return 0;
    int same = strcmp(have, text) == 0;
    free(have);
    return same;
}

/* Writes only on change so mtimes (and codex's hook trust hashes) stay put. */
static int put(const char *path, const char *text, FILE *log)
{
    if (same_text(path, text))
        return 1;
    char dir[PATH_MAX];
    snprintf(dir, sizeof dir, "%s", path);
    char *slash = strrchr(dir, '/');
    if (slash) {
        *slash = '\0';
        if (!mkdir_p(dir))
            return 0;
    }
    if (!text_spit(path, write_text, (void *)text)) {
        fprintf(log, "sync: cannot write %s\n", path);
        return 0;
    }
    fprintf(log, "wrote %s\n", path);
    return 1;
}

static int rm_rf(const char *path)
{
    struct stat st;
    if (lstat(path, &st) != 0)
        return errno == ENOENT;
    if (!S_ISDIR(st.st_mode))
        return unlink(path) == 0;
    DIR *d = opendir(path);
    if (!d)
        return 0;
    struct dirent *e;
    int ok = 1;
    while ((e = readdir(d))) {
        if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, ".."))
            continue;
        char child[PATH_MAX];
        if ((size_t)snprintf(child, sizeof child, "%s/%s", path, e->d_name) >= sizeof child ||
            !rm_rf(child))
            ok = 0;
    }
    closedir(d);
    return ok && rmdir(path) == 0;
}

static int inside(const char *path, const char *root)
{
    size_t n = strlen(root);
    return strncmp(path, root, n) == 0 && (path[n] == '/' || path[n] == '\0');
}

static int sync_skills(const char *home, int prune, FILE *log)
{
    char canon[PATH_MAX], shared[PATH_MAX], real_canon[PATH_MAX];
    if (!at(canon, sizeof canon, home, ".claude/skills") ||
        !at(shared, sizeof shared, home, ".agents/skills"))
        return 0;
    mkdir_p(canon);
    if (!realpath(canon, real_canon))
        return 0;

    struct stat st;
    if (lstat(shared, &st) != 0) {
        char parent[PATH_MAX];
        at(parent, sizeof parent, home, ".agents");
        mkdir_p(parent);
        if (symlink(canon, shared) == 0)
            fprintf(log, "linked %s -> %s\n", shared, canon);
        else
            fprintf(log, "sync: cannot link %s: %s\n", shared, strerror(errno));
    } else {
        char real_shared[PATH_MAX];
        if (!realpath(shared, real_shared) || strcmp(real_shared, real_canon))
            fprintf(log, "note: %s is not a link to %s; leaving it alone\n", shared, canon);
    }

    int stale = 0;
    for (size_t i = 0; i < sizeof OTHER_SKILL_DIRS / sizeof *OTHER_SKILL_DIRS; i++) {
        char dir[PATH_MAX];
        if (!at(dir, sizeof dir, home, OTHER_SKILL_DIRS[i]))
            continue;
        DIR *d = opendir(dir);
        if (!d)
            continue;
        struct dirent *e;
        while ((e = readdir(d))) {
            if (e->d_name[0] == '.')
                continue;
            char entry[PATH_MAX], twin[PATH_MAX];
            if ((size_t)snprintf(entry, sizeof entry, "%s/%s", dir, e->d_name) >= sizeof entry ||
                (size_t)snprintf(twin, sizeof twin, "%s/%s", canon, e->d_name) >= sizeof twin)
                continue;
            int in_canon = stat(twin, &st) == 0;
            if (lstat(entry, &st) != 0)
                continue;
            if (S_ISLNK(st.st_mode)) {
                char target[PATH_MAX];
                int redundant = realpath(entry, target) && inside(target, real_canon);
                if (!redundant && !in_canon)
                    continue;
                if (unlink(entry) == 0)
                    fprintf(log, "removed link %s (%s)\n", entry,
                            redundant ? "points into ~/.agents/skills" : "shadowed by canonical skill");
                continue;
            }
            if (!in_canon)
                continue;
            if (prune) {
                if (rm_rf(entry))
                    fprintf(log, "removed copy %s\n", entry);
                else
                    fprintf(log, "sync: cannot remove %s\n", entry);
            } else {
                fprintf(log, "stale copy %s (canonical: %s)\n", entry, twin);
                stale++;
            }
        }
        closedir(d);
    }
    if (stale)
        fprintf(log, "%d stale skill cop%s; `mux sync --prune` removes them\n",
                stale, stale == 1 ? "y" : "ies");
    return 1;
}

static cJSON *load_json(const char *path)
{
    char *text = text_slurp(path, 4u << 20, NULL);
    if (!text)
        return NULL;
    cJSON *o = cJSON_Parse(text);
    free(text);
    return o;
}

static int save_json(const char *path, const cJSON *o, FILE *log)
{
    char *text = cJSON_Print(o);
    if (!text)
        return 0;
    char *with_nl = text_dsprintf("%s\n", text);
    free(text);
    int ok = with_nl && put(path, with_nl, log);
    free(with_nl);
    return ok;
}

static int is_backend_key(const char *key)
{
    for (size_t i = 0; i < sizeof BACKENDS / sizeof *BACKENDS; i++)
        if (!strcmp(key, BACKENDS[i]))
            return 1;
    return 0;
}

/* One handler as a backend sees it: NULL when dropped there. */
static cJSON *render_handler(const cJSON *h, const char *backend)
{
    const cJSON *over = cJSON_GetObjectItemCaseSensitive(h, backend);
    if (over && cJSON_IsFalse(over))
        return NULL;
    cJSON *out = cJSON_CreateObject();
    for (const cJSON *f = h->child; f; f = f->next) {
        if (is_backend_key(f->string))
            continue;
        if (!strcmp(f->string, "command") && over && cJSON_IsString(over)) {
            cJSON_AddStringToObject(out, "command", over->valuestring);
            continue;
        }
        cJSON_AddItemToObject(out, f->string, cJSON_Duplicate(f, 1));
    }
    return out;
}

static int event_allowed(const char *event, const char *backend)
{
    if (strcmp(backend, "codex"))
        return 1;
    for (size_t i = 0; i < sizeof CODEX_EVENTS / sizeof *CODEX_EVENTS; i++)
        if (!strcmp(event, CODEX_EVENTS[i]))
            return 1;
    return 0;
}

static cJSON *render_hooks(const cJSON *src, const char *backend)
{
    cJSON *out = cJSON_CreateObject();
    for (const cJSON *ev = src ? src->child : NULL; ev; ev = ev->next) {
        if (!cJSON_IsArray(ev) || !event_allowed(ev->string, backend))
            continue;
        cJSON *groups = cJSON_CreateArray();
        const cJSON *g;
        cJSON_ArrayForEach(g, ev) {
            cJSON *handlers = cJSON_CreateArray();
            const cJSON *h;
            cJSON_ArrayForEach(h, cJSON_GetObjectItemCaseSensitive(g, "hooks")) {
                cJSON *r = render_handler(h, backend);
                if (r)
                    cJSON_AddItemToArray(handlers, r);
            }
            if (!cJSON_GetArraySize(handlers)) {
                cJSON_Delete(handlers);
                continue;
            }
            cJSON *group = cJSON_CreateObject();
            const cJSON *m = cJSON_GetObjectItemCaseSensitive(g, "matcher");
            if (cJSON_IsString(m))
                cJSON_AddStringToObject(group, "matcher", m->valuestring);
            cJSON_AddItemToObject(group, "hooks", handlers);
            cJSON_AddItemToArray(groups, group);
        }
        if (cJSON_GetArraySize(groups))
            cJSON_AddItemToObject(out, ev->string, groups);
        else
            cJSON_Delete(groups);
    }
    return out;
}

static const cJSON *handler_at(const cJSON *hooks, const char *event, int gi, int hi)
{
    const cJSON *g = cJSON_GetArrayItem(cJSON_GetObjectItemCaseSensitive(hooks, event), gi);
    return cJSON_GetArrayItem(cJSON_GetObjectItemCaseSensitive(g, "hooks"), hi);
}

/* First run: Claude's hooks become the source, with codex's existing commands
   folded in as overrides where they differ and codex-only events kept off
   Claude. */
static cJSON *seed_hooks(const char *home, FILE *log)
{
    char path[PATH_MAX];
    cJSON *hooks = NULL;
    if (at(path, sizeof path, home, ".claude/settings.json")) {
        cJSON *settings = load_json(path);
        hooks = cJSON_Duplicate(cJSON_GetObjectItemCaseSensitive(settings, "hooks"), 1);
        cJSON_Delete(settings);
    }
    if (!hooks)
        hooks = cJSON_CreateObject();

    cJSON *codex = at(path, sizeof path, home, ".codex/hooks.json") ? load_json(path) : NULL;
    const cJSON *codex_hooks = cJSON_GetObjectItemCaseSensitive(codex, "hooks");
    cJSON *ev;
    cJSON_ArrayForEach(ev, hooks) {
        int gi = 0;
        cJSON *g;
        cJSON_ArrayForEach(g, ev) {
            int hi = 0;
            cJSON *h;
            cJSON_ArrayForEach(h, cJSON_GetObjectItemCaseSensitive(g, "hooks")) {
                const cJSON *mine = cJSON_GetObjectItemCaseSensitive(h, "command");
                const cJSON *theirs = cJSON_GetObjectItemCaseSensitive(
                    handler_at(codex_hooks, ev->string, gi, hi), "command");
                if (cJSON_IsString(mine) && cJSON_IsString(theirs) &&
                    strcmp(mine->valuestring, theirs->valuestring))
                    cJSON_AddStringToObject(h, "codex", theirs->valuestring);
                hi++;
            }
            gi++;
        }
    }
    const cJSON *cev;
    cJSON_ArrayForEach(cev, codex_hooks) {
        if (cJSON_GetObjectItemCaseSensitive(hooks, cev->string))
            continue;
        cJSON *copy = cJSON_Duplicate(cev, 1);
        cJSON *g;
        cJSON_ArrayForEach(g, copy) {
            cJSON *h;
            cJSON_ArrayForEach(h, cJSON_GetObjectItemCaseSensitive(g, "hooks"))
                cJSON_AddFalseToObject(h, "claude");
        }
        cJSON_AddItemToObject(hooks, cev->string, copy);
    }
    cJSON_Delete(codex);

    cJSON *root = cJSON_CreateObject();
    cJSON_AddItemToObject(root, "hooks", hooks);
    fprintf(log, "seeded hooks from ~/.claude/settings.json\n");
    return root;
}

static int sync_hooks(const char *home, FILE *log)
{
    char path[PATH_MAX];
    if (!at(path, sizeof path, home, ".config/mux/hooks.json"))
        return 0;
    cJSON *root = load_json(path);
    if (!root) {
        root = seed_hooks(home, log);
        if (!save_json(path, root, log)) {
            cJSON_Delete(root);
            return 0;
        }
    }
    const cJSON *src = cJSON_GetObjectItemCaseSensitive(root, "hooks");

    int ok = 1;
    if (at(path, sizeof path, home, ".claude/settings.json")) {
        cJSON *settings = load_json(path);
        if (!settings)
            settings = cJSON_CreateObject();
        cJSON_DeleteItemFromObjectCaseSensitive(settings, "hooks");
        cJSON_AddItemToObject(settings, "hooks", render_hooks(src, "claude"));
        ok &= save_json(path, settings, log);
        cJSON_Delete(settings);
    }
    if (at(path, sizeof path, home, ".codex/hooks.json")) {
        cJSON *codex = cJSON_CreateObject();
        cJSON_AddItemToObject(codex, "hooks", render_hooks(src, "codex"));
        ok &= save_json(path, codex, log);
        cJSON_Delete(codex);
    }
    if (at(path, sizeof path, home, ".pi/agent/extensions/mux-hooks.ts"))
        ok &= put(path, PI_EXTENSION, log);

    cJSON_Delete(root);
    return ok;
}

int agentsync_run(const char *home, int prune, FILE *log)
{
    if (!home || !*home)
        return 0;
    int ok = sync_skills(home, prune, log);
    ok &= sync_hooks(home, log);
    return ok;
}

int agentsync_main(int argc, char **argv)
{
    int prune = 0;
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--prune"))
            prune = 1;
        else {
            fprintf(stderr, "usage: mux sync [--prune]\n");
            return 2;
        }
    }
    return agentsync_run(getenv("HOME"), prune, stdout) ? 0 : 1;
}
