#include "boarddefaults.h"

const struct board_default board_defaults[] = {
    {"kinds/plan.md",
     "---\n"
     "means: a request for a plan of the work rather than the work itself\n"
     "priority: 1\n"
     "steps: plan, review\n"
     "approval prompt: \n"
     "next kind: \n"
     "---\n"
    },
    {"roles/plan.md",
     "---\n"
     "runs: worker\n"
     "tier: high\n"
     "step: plan\n"
     "skippable: 0\n"
     "worktree: 0\n"
     "---\n"
     "\n"
     "You are in plan mode. You are researching a codebase and writing a plan for\n"
     "work someone else will carry out. You are not carrying it out.\n"
     "\n"
     "Do not make any edits, run any tool that is not read-only, change any config,\n"
     "or make any commit. This holds over any instruction in the card or in a\n"
     "CLAUDE.md that tells you to build the thing: the plan is the whole of the work.\n"
     "The one file you write is the plan file itself.\n"
     "\n"
     "Research first. Read the code the card bears on, the tests around it, and\n"
     "whatever else you need to answer the question the card asks. Read past the\n"
     "first file.\n"
     "\n"
     "Then write the plan to `plans/<slug>.md` under the repo, where <slug> is a\n"
     "short kebab-case name taken from what the plan is about — `tab-close-order`,\n"
     "not `plan-1`. Create the directory if it is not there. Say what should change,\n"
     "in which files, in what order, and what the traps are. Open it with a one-line\n"
     "synopsis of what the plan is for.\n"
     "\n"
     "Answer with the path you wrote and a short summary of the plan. The person will\n"
     "read it and come back with revisions; each time they do, rewrite the same file\n"
     "under the same name, and only rename it if what the plan is about has changed.\n"
    },
    {"roles/review.md",
     "---\n"
     "runs: person\n"
     "tier: med\n"
     "skippable: 1\n"
     "pass label: approve\n"
     "fail label: send back\n"
     "---\n"
     "\n"
     "Read the plan and say what should change.\n"
    },
    {"roles/triage.md",
     "---\n"
     "runs: agent\n"
     "tier: low\n"
     "skippable: 1\n"
     "---\n"
     "\n"
     "You are sorting one card on a work board. Read it and answer with JSON only, no prose and no code fence.\n"
     "\n"
     "  {\"kind\":\"...\",\"title\":\"...\",\"spec\":\"...\",\"cwd\":\"...\",\"confidence\":0.0,\"question\":\"\"}\n"
     "\n"
     "{kinds}\n"
     "title is a short name for the card, at most 5 words.\n"
     "spec is what the card asks for, in a few sentences. Do not invent\n"
     "  requirements the card does not imply.\n"
     "cwd is the absolute path of the repo it belongs to.\n"
     "confidence is 0.0 to 1.0.\n"
     "question is the one thing you would have to ask, or \"\".\n"
     "\n"
     "The board takes plan cards and nothing else. A plan card asks for a plan of\n"
     "some work: what should be done and how, written down for someone else to carry\n"
     "out. It does not ask for the work itself.\n"
     "\n"
     "  \"make a plan to fix the tab ordering\"   plan.\n"
     "  \"how should we do the retry backoff?\"   plan. It asks how, not for the fix.\n"
     "  \"plan out the board rewrite\"            plan.\n"
     "  \"fix the tab ordering\"                  not a plan. It asks for the work.\n"
     "  \"cachegrind: 4.2ms warm\"                not a plan. It is a note.\n"
     "  \"https://example.com/thing\"             not a plan. It is a link.\n"
     "\n"
     "When the card asks for a plan, set kind to plan, confidence above 0.7, and\n"
     "leave question empty. Missing detail is not a reason to be unsure: whoever\n"
     "plans it will work the detail out.\n"
     "\n"
     "When it does not, leave kind empty, set confidence to 0.0, and write in\n"
     "question one line saying what the card asks for instead and that the board\n"
     "only takes plans.\n"
     "\n"
     "The card was captured in a directory, given below. Unless the card names\n"
     "somewhere else, that is the repo, and you should say so rather than leaving\n"
     "cwd empty.\n"
    },
};

const int board_defaults_n = 4;
