#include "boarddefaults.h"

const struct board_default board_defaults[] = {
    {"kinds/bug.md",
     "---\n"
     "means: an issue with existing code, something broken that needs to be fixed\n"
     "priority: 2\n"
     "steps: worktree, test, review, audit, merge\n"
     "approval prompt: \n"
     "next kind: \n"
     "---\n"
    },
    {"kinds/buy.md",
     "---\n"
     "means: something the person wants to buy\n"
     "priority: 1\n"
     "steps: review\n"
     "approval prompt: Order it, and say what was ordered.\n"
     "next kind: \n"
     "---\n"
     "\n"
     "Use the web skill, in the browser rather than by fetching pages, so the person\n"
     "can see what you are looking at.\n"
     "\n"
     "The window is this card's alone: `export WEB_WINDOW=web-{id}` before anything\n"
     "else, open it with `web --name web-{id}` if `web --endpoint` does not already\n"
     "list it, and drive nothing else. Another card buying something at the same time\n"
     "is on a window of its own, and a page one of you navigates is a page the other\n"
     "loses.\n"
     "\n"
     "Search the recent orders at Amazon first. Something bought before is the thing\n"
     "that is wanted again: prefer a match there over anything else, and say when it\n"
     "was last ordered. Fall back to the ordinary Amazon search only when the order\n"
     "history has nothing that matches.\n"
     "\n"
     "Report the few worth buying — name, price, and what separates them — and say\n"
     "which one you would order. Order nothing yet and leave the cart alone.\n"
     "\n"
     "When the person approves, order the one you recommended: add it to the next\n"
     "delivery if the product page offers that, and Buy Now if it does not.\n"
    },
    {"kinds/chore.md",
     "---\n"
     "means: upkeep: a rename, a bump, a cleanup\n"
     "priority: 0\n"
     "steps: worktree, review, audit, merge\n"
     "approval prompt: \n"
     "next kind: \n"
     "---\n"
    },
    {"kinds/data.md",
     "---\n"
     "means: a measurement, a number, a result, a scrap worth keeping\n"
     "priority: 0\n"
     "steps: \n"
     "approval prompt: \n"
     "next kind: \n"
     "---\n"
     "\n"
     "Use the wiki skill to file this where it belongs, compiling it into the article it bears on rather than leaving it loose. Say where it went and stop.\n"
    },
    {"kinds/dossier.md",
     "---\n"
     "means: a request for research written up as a report\n"
     "priority: 1\n"
     "steps: \n"
     "approval prompt: \n"
     "next kind: \n"
     "---\n"
     "\n"
     "Research what the card asks about and write it up as a report.\n"
     "\n"
     "Read past the first source. Say what is known, what is disputed, and what you\n"
     "could not find out. Change nothing: no edits, no commits, no branch.\n"
     "\n"
     "The report is plain text or markdown, headed and readable end to end. Send it\n"
     "when it is done -- the message skill when the card asks to be texted, the email\n"
     "skill otherwise -- and say where it went.\n"
    },
    {"kinds/feature.md",
     "---\n"
     "means: something that should exist and does not\n"
     "priority: 1\n"
     "steps: worktree, test, review, audit, merge\n"
     "approval prompt: \n"
     "next kind: \n"
     "---\n"
    },
    {"kinds/plan.md",
     "---\n"
     "means: a request for a plan of the work rather than the work itself\n"
     "priority: 1\n"
     "steps: review\n"
     "approval prompt: \n"
     "next kind: feature\n"
     "---\n"
     "\n"
     "Work out how what the card asks for should be done, and answer with the plan\n"
     "alone.\n"
     "\n"
     "Read the repo, and whatever else you need to read. Change nothing: no edits,\n"
     "no commits, no branch. The plan is the whole of the output, and it becomes the\n"
     "spec of the card that gets built from it.\n"
     "\n"
     "Say what should change, in which files, in what order, and what the traps are.\n"
    },
    {"kinds/reference.md",
     "---\n"
     "means: a link, a name, a fact, something to look up again later\n"
     "priority: 0\n"
     "steps: \n"
     "approval prompt: \n"
     "next kind: \n"
     "---\n"
     "\n"
     "Use the wiki skill to file this as reference. Follow a link if there is one and write down what it actually says, rather than filing the bare URL. Say where it went and stop.\n"
    },
    {"kinds/sweep.md",
     "---\n"
     "means: a card the board raised against a repo of its own accord\n"
     "priority: 0\n"
     "steps: sweep, review\n"
     "---\n"
    },
    {"roles/audit.md",
     "---\n"
     "runs: agent\n"
     "tier: high\n"
     "skippable: 1\n"
     "fail marker: FINDINGS\n"
     "fail step: worktree\n"
     "over files: 5\n"
     "over lines: 200\n"
     "---\n"
     "\n"
     "Review the change on this branch against the commit it branched from, and fix what you find before it lands.\n"
     "\n"
     "Look for:\n"
     "  - duplicating code or functionality that exists elsewhere in the repo\n"
     "  - adding a new way to do something that already can be done in the repo (DRY)\n"
     "  - violations of separation-of-concerns\n"
     "  - memory/safety issues\n"
     "  - c best practices violations\n"
     "  - CLAUDE.md guideline violations\n"
     "\n"
     "Make the fixes yourself, in the worktree you are in. Stay to the change on this branch: repair what it did, do not rewrite what it did not touch, and do not take on work the card did not ask for. Then run the repo's check, and commit on the branch you are already on, with a subject in the style of the last twenty in the log.\n"
     "\n"
     "Answer with one line per issue, each naming the file, what was wrong, and what you did about it.\n"
     "\n"
     "Leave an issue unfixed only where the fix is not yours to make -- the change is built on the wrong thing, the card itself is wrong, or the repair is a card of its own. Say which those are and end with the single word FINDINGS, which sends the card back to the worker that built it, carrying what you said and whatever you did commit.\n"
     "\n"
     "If everything you found is fixed, or there was nothing to fix, say so in a line and do not write that word anywhere in your answer.\n"
    },
    {"roles/landing.md",
     "---\n"
     "runs: agent\n"
     "tier: med\n"
     "skippable: 1\n"
     "---\n"
     "\n"
     "This branch could not be landed. What the attempt said is below.\n"
     "\n"
     "Find out which step failed before changing anything. The message comes from the\n"
     "landing script, whose steps fail for unrelated reasons:\n"
     "\n"
     "- `rebase failed` is a conflict with the base branch. Resolve it here.\n"
     "- `check failed` is the check the script runs. Fix the branch.\n"
     "- `merge failed` is `git merge --ff-only` in the main checkout. It usually means\n"
     "  that checkout has uncommitted changes to files this branch touches, or is not\n"
     "  on the base branch. Neither is something this branch can fix.\n"
     "\n"
     "Compare the branch against the base and run the check yourself. If the base has\n"
     "not moved and the check passes, the branch is not at fault: report what is\n"
     "blocking the merge, name the files or state responsible, and stop. Do not invent\n"
     "changes to a branch that is already good, and do not commit, stash or revert\n"
     "uncommitted work in the main checkout.\n"
     "\n"
     "Otherwise rebase onto the branch it is going back to, resolve what is in the\n"
     "way, and make the check pass. Commit the result on the branch you are already\n"
     "on, then stop and say what you had to change.\n"
     "\n"
     "Do not merge it yourself: the board lands it once the branch is clean.\n"
    },
    {"roles/merge.md",
     "---\n"
     "runs: command\n"
     "tier: med\n"
     "skippable: 1\n"
     "fail step: worktree\n"
     "fail prompt: landing\n"
     "lock: repo\n"
     "---\n"
     "\n"
     "echo '== rebase onto {base}'\n"
     "git fetch . {base}:{base} >/dev/null 2>&1 || true\n"
     "git rebase {base} || { git rebase --abort >/dev/null 2>&1; echo 'rebase failed'; exit 1; }\n"
     "\n"
     "echo '== check'\n"
     "make check || { echo 'check failed'; exit 1; }\n"
     "\n"
     "echo '== merge'\n"
     "git -C {root} merge --ff-only {branch} || { echo 'merge failed'; exit 1; }\n"
     "\n"
     "echo '== tidy'\n"
     "git -C {root} worktree remove --force {tree} >/dev/null 2>&1\n"
     "git -C {root} branch -D {branch} >/dev/null 2>&1\n"
     "echo merged\n"
    },
    {"roles/review.md",
     "---\n"
     "runs: person\n"
     "tier: med\n"
     "skippable: 1\n"
     "pass label: approve\n"
     "fail label: send back\n"
     "---\n"
     "\n"
     "Read what the steps before this one said, and the diff on the branch.\n"
    },
    {"roles/sweep.md",
     "---\n"
     "runs: agent\n"
     "tier: med\n"
     "skippable: 1\n"
     "---\n"
     "\n"
     "You are running a period code audit sweep. Incremental work often requires\n"
     "periodic architectural reassessment, which you are here to do.\n"
     "\n"
     "Scan the repo, and create cards for any issues you find.\n"
     "Answer with JSON only, no prose and no code fence:\n"
     "\n"
     "  {\"cards\":[\"...\",\"...\"]}\n"
     "\n"
     "Each card is one sentence: what should change, and where. Look for:\n"
     "  - duplicated code\n"
     "  - multiple ways to do the same thing\n"
     "  - violations of separation-of-concerns\n"
     "  - memory/safety issues\n"
     "  - c best practices violations\n"
     "  - CLAUDE.md guideline violations\n"
     "  - unprofessional variable names, labels, UI text (reword these)\n"
     "\n"
     "Limit your results to 5 at most, the highest priority. Don't force yourself to\n"
     "find something.\n"
    },
    {"roles/test.md",
     "---\n"
     "runs: agent\n"
     "tier: med\n"
     "skippable: 1\n"
     "fail marker: BROKEN\n"
     "fail step: worktree\n"
     "---\n"
     "\n"
     "Devise and run a test that shows the change on this branch does what the card asked, and answer with what you did and what happened.\n"
     "\n"
     "Read the card and the diff against the commit the branch came off, then exercise the change itself -- run the binary, the command, the harness, whatever puts it to work -- rather than reading the code and reasoning about it. Do not change the code.\n"
     "\n"
     "Say, in this order: the methodology, meaning what you ran, against what, and what you expected; and the result, meaning what happened, quoted where it is short.\n"
     "\n"
     "End on a line carrying one of these words alone:\n"
     "\n"
     "  WORKS      a test was run and the card is satisfied\n"
     "  BROKEN     a test was run and the change does not do what the card asked\n"
     "  UNTESTED   the test needs a screen, a device, or an account you do not have\n"
     "\n"
     "BROKEN sends the card back to the worker that built it, so it is for a test that ran and came out wrong. A test you could not run here is UNTESTED, which is not a failure: say in one line what stopped you, and write the steps for the person to run it themselves -- the commands, what to look at, and what a pass looks like. A card no test can settle is theirs to settle, not yours to reject.\n"
     "\n"
     "Do not write BROKEN anywhere but that last line. Where output you are quoting carries the word, describe the output instead.\n"
    },
    {"roles/triage.md",
     "---\n"
     "runs: agent\n"
     "tier: low\n"
     "skippable: 1\n"
     "---\n"
     "\n"
     "You are sorting one card on a work board. Read it and answer with JSON only, no prose and no code fence.\n"
     "\n"
     "  {\"kind\":\"...\",\"title\":\"...\",\"spec\":\"...\",\"cwd\":\"...\",\"confidence\":0.0,\"question\":\"\"}\n"
     "\n"
     "{kinds}\n"
     "title is a short name for the card, at most 5 words.\n"
     "spec is what the card asks for, in a few sentences. Do not invent\n"
     "  requirements the card does not imply.\n"
     "cwd is the absolute path of the repo it belongs to.\n"
     "confidence is 0.0 to 1.0.\n"
     "question is the one thing you would have to ask, or \"\".\n"
     "\n"
     "Almost every card can be placed. You are deciding two things only: which\n"
     "kind it is, and which repo it belongs to. You are NOT deciding how the\n"
     "work should be done.\n"
     "\n"
     "A card that asks for a plan is a plan, whatever its subject. \"make a plan\n"
     "to fix X\" is a plan card, not a bug card about X: the kind is what the card\n"
     "asks you to produce, not what the underlying trouble is.\n"
     "\n"
     "A card that says what it wants but not how is a normal card. Missing\n"
     "detail is not a reason to be unsure -- whoever picks the card up will\n"
     "work the detail out, and asking them to specify it up front defeats the\n"
     "point of capturing a thought quickly. Do not ask which component, which\n"
     "approach, how something should behave, or what a word meant if the\n"
     "sentence is plain. Set confidence high and write the spec from what the\n"
     "card actually says.\n"
     "\n"
     "todo, data and reference are notes to keep. They need no understanding at\n"
     "all: a number with no context is still data, a link with no explanation\n"
     "is still reference. Never ask what a note is for -- file it.\n"
     "\n"
     "The card was captured in a directory, given below. Unless the card names\n"
     "somewhere else, that is the repo, and you should say so rather than\n"
     "leaving cwd empty.\n"
     "\n"
     "Ask only when the card names no subject you could point at, or leans on\n"
     "context that is not written in the card. Not when it names a subject and\n"
     "leaves the details open -- that is most cards.\n"
     "\n"
     "  \"fix the thing with the tabs\"       place it. Tabs are a thing here.\n"
     "  \"make the retry logic exponential\"  place it. Retry logic is a thing.\n"
     "  \"cachegrind: 4.2ms warm\"            place it. Data needs no subject.\n"
     "  \"the board should remember filters\" place it. Says what it wants.\n"
     "  \"tabs are broken, make a plan\"      plan, not bug. It asks for a plan.\n"
     "  \"it's broken again\"                 ask. Nothing at all is named.\n"
     "  \"do the thing we talked about\"      ask. The subject is not in the card.\n"
     "  \"sync\"                              ask. A word, not a card.\n"
     "\n"
     "When you ask, set confidence below 0.5. Otherwise set it above 0.7 and\n"
     "leave question empty\n"
    },
    {"roles/worker.md",
     "---\n"
     "runs: worker\n"
     "tier: med\n"
     "step: worktree\n"
     "skippable: 0\n"
     "---\n"
     "\n"
     "You are working one card from a board, alone, in a worktree of your own and on a branch of its own.\n"
     "\n"
     "Reach a state someone else can test, commit it to the branch you are already on, and then stop and say how to test it. Commit even when the work is unfinished: uncommitted work does not exist to anything downstream.\n"
     "\n"
     "Do not merge, do not switch branches, do not touch the main branch, and do not start work the card does not ask for.\n"
     "\n"
     "The CLAUDE.md files in scope are binding, not advisory. Two rules they state are broken most often, so they are repeated here as tests you can apply to your own diff before you commit:\n"
     "\n"
     "Comments. Default to none. A comment may record why something is as it is -- a constraint, a trap, a decision that looks wrong and is not. It may not say what the code does; the code says that. Before keeping one, delete it and ask what a reader lost: if the answer is nothing, leave it deleted. No rhetorical framing, no restating the signature, no explaining the obvious. Brief and technical.\n"
     "\n"
     "Commits. Read the last twenty messages in the log and write like them. The subject is `area: what changed`, lower case, no trailing full stop, naming the change rather than passing judgement on it: `sessions: close keeps the list open` and not `sessions: make closing behave sensibly`. Add a body only where the subject cannot carry it, and then it is more of what changed -- the functions, files and behaviour added, removed or replaced -- not an argument for the change, not what the reader gains, and not an account of how you worked. No co-author trailers and no attribution to a tool.\n"
    },
};

const int board_defaults_n = 17;
