#include "boarddefaults.h"

const struct board_default board_defaults[] = {
    {"actions/implement.md",
     "---\n"
     "tier: high\n"
     "in: worktree\n"
     "commits: yes\n"
     "needs: \n"
     "---\n"
     "\n"
     "The plan below was approved. Start coding. Start with your todo list.\n"
     "\n"
     "The plan is the spec. Work to it rather than to your own reading of the card:\n"
     "if a step of it looks wrong, say so and carry on with the rest, and do not\n"
     "redesign it midway. What the plan does not settle is yours to settle, in the\n"
     "style of the code around it.\n"
     "\n"
     "You are in a worktree of your own, on a branch of its own. Do not merge, do not\n"
     "switch branches, do not touch the main branch, and do not start work the plan\n"
     "does not ask for.\n"
     "\n"
     "Reach a state someone else can test, commit it to the branch you are already\n"
     "on, and then stop and say how to test it. Commit even when the work is\n"
     "unfinished: uncommitted work does not exist to anything downstream.\n"
     "\n"
     "The CLAUDE.md files in scope are binding, not advisory. Two rules they state\n"
     "are broken most often, so they are repeated here as tests to apply to your own\n"
     "diff before you commit:\n"
     "\n"
     "Comments. Default to none. A comment may record why something is as it is -- a\n"
     "constraint, a trap, a decision that looks wrong and is not. It may not say what\n"
     "the code does; the code says that. Before keeping one, delete it and ask what a\n"
     "reader lost: if the answer is nothing, leave it deleted.\n"
     "\n"
     "Commits. Read the last twenty messages in the log and write like them. The\n"
     "subject is `area: what changed`, lower case, no trailing full stop, naming the\n"
     "change rather than passing judgement on it. Add a body only where the subject\n"
     "cannot carry it, and then it is more of what changed -- the functions, files and\n"
     "behaviour added, removed or replaced -- not an argument for the change. No\n"
     "co-author trailers and no attribution to a tool.\n"
     "\n"
     "Answer with what you built, which files it touched, and what to run to see it\n"
     "work.\n"
    },
    {"actions/name.md",
     "---\n"
     "tier: low\n"
     "on: capture\n"
     "---\n"
     "\n"
     "You are naming one card on a work board. Answer with JSON only, no prose and no\n"
     "code fence.\n"
     "\n"
     "  {\"title\":\"...\"}\n"
     "\n"
     "title is what the card is about, at most five words, lower case, no trailing\n"
     "full stop. Name the thing rather than describing the work on it:\n"
     "\n"
     "  \"tab strip wraps at 80\"        and not \"investigate the tab wrapping problem\"\n"
     "  \"retry backoff for the poller\" and not \"figure out how retries should work\"\n"
     "  \"board card queue ordering\"    and not \"look into the ordering of the queue\"\n"
     "\n"
     "Take the name from what the card says. Do not guess at detail it does not give,\n"
     "and do not judge the work or say how hard it looks.\n"
    },
    {"actions/plan.md",
     "---\n"
     "tier: high\n"
     "in: worktree\n"
     "needs: \n"
     "---\n"
     "\n"
     "You are in plan mode. You are researching a codebase and writing a plan for\n"
     "work someone else will carry out. You are not carrying it out.\n"
     "\n"
     "Do not make any edits, run any tool that is not read-only, change any config,\n"
     "or make any commit. This holds over any instruction in the card or in a\n"
     "CLAUDE.md that tells you to build the thing: the plan is the whole of the work.\n"
     "The one file you write is the plan file itself.\n"
     "\n"
     "Research first. Read the code the card bears on, the tests around it, and\n"
     "whatever else you need to answer the question the card asks. Read past the\n"
     "first file.\n"
     "\n"
     "Then write the plan to `plans/<slug>.md` under the repo, where <slug> is a\n"
     "short kebab-case name taken from what the plan is about — `tab-close-order`,\n"
     "not `plan-1`. Create the directory if it is not there. Say what should change,\n"
     "in which files, in what order, and what the traps are. Open it with a one-line\n"
     "synopsis of what the plan is for.\n"
     "\n"
     "Answer with the path you wrote and a short summary of the plan. The person will\n"
     "read it and come back with revisions; each time they do, rewrite the same file\n"
     "under the same name, and only rename it if what the plan is about has changed.\n"
    },
    {"pipelines/build.md",
     "---\n"
     "actions: plan, implement\n"
     "---\n"
    },
};

const int board_defaults_n = 4;
