#include "orchdata.h"

const struct orch_file orch_files[] = {
    {"SKILL.md",
     "---\n"
     "name: orchestrate\n"
     "description: Task orchestrator over mux. Use when the user adds, lists, dispatches, or asks the status of project tasks (\"add a task to mux\", \"what's queued\", \"dispatch it\", \"how's the auth task going\"), or says /orchestrate. Not for dispatched workers: a session whose prompt names it a worker must never invoke this skill.\n"
     "---\n"
     "\n"
     "# orchestrate\n"
     "\n"
     "You are the orchestrator. mux runs the orchestrator subsystem: it owns\n"
     "`~/.config/orchestrator`, watches the workers, folds in results, and messages\n"
     "you when one finishes. You make the judgement calls and drive it through\n"
     "`mux orch`. Never hand-edit the state files — the subsystem writes them under a\n"
     "lock, and a second writer is how records get lost.\n"
     "\n"
     "Delegate anything that takes more than one trivial command. Replies are read\n"
     "aloud: one or two sentences unless asked for a full readout.\n"
     "\n"
     "## Commands\n"
     "\n"
     "    mux orch list [all]               open tasks, or every task\n"
     "    mux orch show <task>              one task in full, with its live state\n"
     "    mux orch projects                 known projects and their directories\n"
     "    mux orch add <project> <text>     queue a task\n"
     "    mux orch status <task> <status>   queued|dispatched|review|done|failed|paused|cancelled\n"
     "    mux orch note <task> <text>       append to its notes\n"
     "    mux orch followup <task> <text>   queue an instruction for its worker\n"
     "    mux orch dispatch <task> <prompt> start a worker\n"
     "    mux orch send <task> <text>       type at its live worker\n"
     "    mux orch reconcile                fold in results now\n"
     "\n"
     "`--json` for machine-readable output, `--project <name>` to disambiguate a task\n"
     "id. If a verb reports that no instance is running the orchestrator, say so and\n"
     "ask the user to start one with `/orchestrator`; do not edit files by hand\n"
     "instead.\n"
     "\n"
     "## Dispatching\n"
     "\n"
     "For a code task make the worktree first:\n"
     "\n"
     "    git -C <project cwd> worktree add .claude/worktrees/<task> -b worktree-<task> master\n"
     "\n"
     "Then one call does the rest — picks the instance, starts the worker, records\n"
     "backend, model and session, moves the task to `dispatched`, and arms the\n"
     "completion notification:\n"
     "\n"
     "    mux orch dispatch <task> \"<prompt>\" --backend claude --model \"opus[1m]\" \\\n"
     "      --cwd <worktree> --title \"<task id without t-> <short desc>\"\n"
     "\n"
     "Choose the backend by running `~/.config/orchestrator/quota.sh` and taking the\n"
     "one with the most left among those `routing.json` lists for the task's class\n"
     "(`planning`, `diagnosis`, `impl`). Nothing more elaborate than that.\n"
     "\n"
     "The worker prompt carries: the task id and description, the cwd, scope limits\n"
     "(touch nothing outside scope, no commits unless the task says so), \"you are a\n"
     "worker — do not invoke the orchestrate skill or dispatch further workers\", and\n"
     "the completion contract:\n"
     "\n"
     "    As your final act write ~/.config/orchestrator/results/<task>.json:\n"
     "    {\"task\", \"status\": \"done\"|\"failed\", \"summary\", \"files\": [], \"commit\", \"finished\"}\n"
     "    summary is one paragraph, sized to be read aloud.\n"
     "\n"
     "A task already dispatched with a live worker is refused. That is deliberate —\n"
     "two workers in one worktree have collided before. Send a follow-up instead.\n"
     "\n"
     "## Judgement\n"
     "\n"
     "- Tasks are for product work: features, fixes, durable deliverables. Ad-hoc\n"
     "  research or a status lookup goes to a one-off subagent with no task record.\n"
     "- Before adding, check `mux orch list` for one covering the same work. A tweak\n"
     "  to something already dispatched is a follow-up, not a new task.\n"
     "- Queued tasks wait for an explicit instruction to dispatch. Never auto-dispatch\n"
     "  one, including when its dependency completes.\n"
     "- `review` means the worker finished; `done` means merged. When the user\n"
     "  approves a `review` task, merge it, then set `done` with the merge commit.\n"
     "- Checkpoint tasks pause the project's dispatching until the user reviews.\n"
     "- Never start a background waiter, polling loop, or heartbeat. The subsystem\n"
     "  messages you when a worker finishes or dies. A line beginning \"orchestrator:\"\n"
     "  is that mechanism talking: act on it and tell the user.\n"
    },
    {"quota.sh",
     "#!/usr/bin/env bash\n"
     "# Read-only real quota snapshot for claude/codex/grok. Prints one JSON object:\n"
     "#   {backend: {remaining_pct, resets_at, read_at, source}}\n"
     "# remaining_pct/resets_at are null when no reading is available.\n"
     "#\n"
     "# Sources:\n"
     "#   claude/codex/grok: mux's agenttabs state dir, written by claude.h/codex.h/grok.h\n"
     "#                 rate_limit hooks whenever mux runs those backends. Falls back to\n"
     "#                 scanning codex CLI session jsonl (~/.codex/sessions) for codex only.\n"
     "set -euo pipefail\n"
     "\n"
     "now=$(date +%s)\n"
     "\n"
     "state_dir() {\n"
     "    if [ -n \"${AGENT_TABS_STATE_DIR:-}\" ]; then\n"
     "        echo \"$AGENT_TABS_STATE_DIR\"\n"
     "        return\n"
     "    fi\n"
     "    local base=\"$HOME/.config/tmux\"\n"
     "    local legacy=\"$HOME/.tmux\"\n"
     "    if [ ! -d \"$base\" ] && [ -d \"$legacy\" ]; then\n"
     "        base=\"$legacy\"\n"
     "    fi\n"
     "    echo \"$base/tmux-agent-tabs\"\n"
     "}\n"
     "\n"
     "agents_dir=\"$(state_dir)/agents\"\n"
     "\n"
     "# Latest usage reading for one backend name from mux's agent-tab records.\n"
     "# Emits {remaining_pct, resets_at, read_at, source} or \"null\".\n"
     "latest_from_agenttabs() {\n"
     "    local backend=\"$1\"\n"
     "    [ -d \"$agents_dir\" ] || { echo \"null\"; return; }\n"
     "    jq -s --arg backend \"$backend\" --arg src \"mux agenttabs: $agents_dir\" '\n"
     "        map(select(.agent == $backend and (.usage_percent != null)))\n"
     "        | sort_by(.usage_ts) | last\n"
     "        | if . == null then null else {\n"
     "            remaining_pct: (100 - .usage_percent),\n"
     "            resets_at: .usage_resets_at,\n"
     "            read_at: .usage_ts,\n"
     "            source: $src\n"
     "          } end\n"
     "    ' \"$agents_dir\"/*.json 2>/dev/null || echo \"null\"\n"
     "}\n"
     "\n"
     "# Fallback for codex: scan recent session jsonl files for the latest\n"
     "# token_count event's rate_limits.primary block.\n"
     "latest_from_codex_sessions() {\n"
     "    local sessions_dir=\"$HOME/.codex/sessions\"\n"
     "    [ -d \"$sessions_dir\" ] || { echo \"null\"; return; }\n"
     "    local f\n"
     "    f=$(find \"$sessions_dir\" -iname '*.jsonl' -newermt '-7 days' -print0 2>/dev/null \\\n"
     "        | xargs -0 ls -t 2>/dev/null | head -1)\n"
     "    [ -n \"$f\" ] || { echo \"null\"; return; }\n"
     "    /usr/bin/grep '\"rate_limits\"' \"$f\" 2>/dev/null | tail -1 | jq --arg src \"codex session jsonl: $f\" '\n"
     "        .payload.rate_limits.primary as $p\n"
     "        | if $p == null then null else {\n"
     "            remaining_pct: (100 - $p.used_percent),\n"
     "            resets_at: $p.resets_at,\n"
     "            read_at: (.timestamp | fromdateiso8601),\n"
     "            source: $src\n"
     "          } end\n"
     "    ' 2>/dev/null || echo \"null\"\n"
     "}\n"
     "\n"
     "claude=$(latest_from_agenttabs claude)\n"
     "codex=$(latest_from_agenttabs codex)\n"
     "if [ \"$codex\" = \"null\" ]; then\n"
     "    codex=$(latest_from_codex_sessions)\n"
     "fi\n"
     "grok=$(latest_from_agenttabs grok)\n"
     "\n"
     "jq -n --argjson claude \"$claude\" --argjson codex \"$codex\" --argjson grok \"$grok\" \\\n"
     "    '{claude: $claude, codex: $codex, grok: $grok}'\n"
    },
    {"routing.json",
     "{\n"
     "  \"classes\": {\n"
     "    \"planning\":  [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                  {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "    \"diagnosis\": [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                  {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "    \"impl\":      [{\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "                  {\"backend\": \"grok\", \"model\": \"grok-4.6\"},\n"
     "                  {\"backend\": \"codex\", \"model\": \"sol\"}]\n"
     "  },\n"
     "  \"orchestrator\": {\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "  \"seed_cost\": {\"planning\": 3, \"diagnosis\": 2, \"impl\": 5},\n"
     "  \"budgets\": {}\n"
     "}\n"
    },
};

const int orch_files_n = 3;
