#include "orchdata.h"

const struct orch_file orch_files[] = {
    {"SKILL.md",
     "---\n"
     "name: orchestrate\n"
     "description: Voice-first task orchestrator over mux. Use when the user adds, lists, dispatches, or asks status of project tasks (\"add a task to mux\", \"what's queued\", \"dispatch it\", \"how's the auth task going\", \"here's a plan for X\"), or says /orchestrate. Not for dispatched workers: a session whose prompt names it a dispatched worker must never invoke this skill.\n"
     "---\n"
     "\n"
     "# orchestrate\n"
     "\n"
     "You are the orchestrator: one session that stays free for instruction and\n"
     "delegates all work. Never implement a task yourself in this role — dispatch\n"
     "it. Stay unblocked: turns are only state-file reads/writes and dispatch\n"
     "requests. Investigation, locating code, checking repos, deploys, and any\n"
     "multi-step lookup go to a worker or background agent, never inline. Keep every reply sized for TTS: one or two sentences unless asked for a\n"
     "full readout.\n"
     "\n"
     "## State\n"
     "\n"
     "All state is in `~/.config/orchestrator/`. Schemas: references/schemas.md\n"
     "next to this skill (read it before writing any record for the first time).\n"
     "\n"
     "- `registry.json` — project name → cwd. Resolve spoken project references\n"
     "  (exact name, then alias, case-insensitive) before anything else; if a name\n"
     "  doesn't resolve, ask, then save the new name or alias.\n"
     "- `projects/<name>.jsonl` — append-only task log, newest record per id wins.\n"
     "- `results/<task-id>.json` — worker-written completion signal.\n"
     "- `routing.json`, `usage.json` — class → models, quota estimates.\n"
     "- `log.jsonl` — event log for digests.\n"
     "\n"
     "## Routing index\n"
     "\n"
     "Load the matching reference only when its situation arises:\n"
     "\n"
     "- Adding, listing, editing, completing tasks → `references/tasks.md`\n"
     "- Turning a plan or a spoken braindump into tasks → `references/intake.md`\n"
     "- Dispatching work to a worker session → `references/dispatch.md`\n"
     "- Checking on workers, digests, probes, checkpoints → `references/monitor.md`\n"
     "- User stepping away or returning → `references/afk.md`\n"
     "- Persisting learned knowledge, archiving old records → `references/stow.md`\n"
     "- Standing feedback on orchestrator behavior → `references/update.md`\n"
     "\n"
     "## Rules\n"
     "\n"
     "- On load, reconcile before anything else (references/monitor.md): pick up\n"
     "  results that arrived while no orchestrator was running, flag orphaned\n"
     "  in-flight work, restart waiters for still-running dispatches.\n"
     "\n"
     "- Task classes: `planning`, `diagnosis`, `impl`. Class decides the model per\n"
     "  routing.json.\n"
     "- Answer status questions from state files first; only probe a worker when\n"
     "  the files can't answer.\n"
     "- Every dispatch, result, and reassignment appends one line to `log.jsonl`.\n"
     "- Checkpoint tasks pause the project's dispatching until the user reviews.\n"
    },
    {"quota.sh",
     "#!/usr/bin/env bash\n"
     "# Read-only real quota snapshot for claude/codex/grok. Prints one JSON object:\n"
     "#   {backend: {remaining_pct, resets_at, read_at, source}}\n"
     "# remaining_pct/resets_at are null when no reading is available.\n"
     "#\n"
     "# Sources:\n"
     "#   claude/codex/grok: mux's agenttabs state dir, written by claude.h/codex.h/grok.h\n"
     "#                 rate_limit hooks whenever mux runs those backends. Falls back to\n"
     "#                 scanning codex CLI session jsonl (~/.codex/sessions) for codex only.\n"
     "set -euo pipefail\n"
     "\n"
     "now=$(date +%s)\n"
     "\n"
     "state_dir() {\n"
     "    if [ -n \"${AGENT_TABS_STATE_DIR:-}\" ]; then\n"
     "        echo \"$AGENT_TABS_STATE_DIR\"\n"
     "        return\n"
     "    fi\n"
     "    local base=\"$HOME/.config/tmux\"\n"
     "    local legacy=\"$HOME/.tmux\"\n"
     "    if [ ! -d \"$base\" ] && [ -d \"$legacy\" ]; then\n"
     "        base=\"$legacy\"\n"
     "    fi\n"
     "    echo \"$base/tmux-agent-tabs\"\n"
     "}\n"
     "\n"
     "agents_dir=\"$(state_dir)/agents\"\n"
     "\n"
     "# Latest usage reading for one backend name from mux's agent-tab records.\n"
     "# Emits {remaining_pct, resets_at, read_at, source} or \"null\".\n"
     "latest_from_agenttabs() {\n"
     "    local backend=\"$1\"\n"
     "    [ -d \"$agents_dir\" ] || { echo \"null\"; return; }\n"
     "    jq -s --arg backend \"$backend\" --arg src \"mux agenttabs: $agents_dir\" '\n"
     "        map(select(.agent == $backend and (.usage_percent != null)))\n"
     "        | sort_by(.usage_ts) | last\n"
     "        | if . == null then null else {\n"
     "            remaining_pct: (100 - .usage_percent),\n"
     "            resets_at: .usage_resets_at,\n"
     "            read_at: .usage_ts,\n"
     "            source: $src\n"
     "          } end\n"
     "    ' \"$agents_dir\"/*.json 2>/dev/null || echo \"null\"\n"
     "}\n"
     "\n"
     "# Fallback for codex: scan recent session jsonl files for the latest\n"
     "# token_count event's rate_limits.primary block.\n"
     "latest_from_codex_sessions() {\n"
     "    local sessions_dir=\"$HOME/.codex/sessions\"\n"
     "    [ -d \"$sessions_dir\" ] || { echo \"null\"; return; }\n"
     "    local f\n"
     "    f=$(find \"$sessions_dir\" -iname '*.jsonl' -newermt '-7 days' -print0 2>/dev/null \\\n"
     "        | xargs -0 ls -t 2>/dev/null | head -1)\n"
     "    [ -n \"$f\" ] || { echo \"null\"; return; }\n"
     "    /usr/bin/grep '\"rate_limits\"' \"$f\" 2>/dev/null | tail -1 | jq --arg src \"codex session jsonl: $f\" '\n"
     "        .payload.rate_limits.primary as $p\n"
     "        | if $p == null then null else {\n"
     "            remaining_pct: (100 - $p.used_percent),\n"
     "            resets_at: $p.resets_at,\n"
     "            read_at: (.timestamp | fromdateiso8601),\n"
     "            source: $src\n"
     "          } end\n"
     "    ' 2>/dev/null || echo \"null\"\n"
     "}\n"
     "\n"
     "claude=$(latest_from_agenttabs claude)\n"
     "codex=$(latest_from_agenttabs codex)\n"
     "if [ \"$codex\" = \"null\" ]; then\n"
     "    codex=$(latest_from_codex_sessions)\n"
     "fi\n"
     "grok=$(latest_from_agenttabs grok)\n"
     "\n"
     "jq -n --argjson claude \"$claude\" --argjson codex \"$codex\" --argjson grok \"$grok\" \\\n"
     "    '{claude: $claude, codex: $codex, grok: $grok}'\n"
    },
    {"references/afk.md",
     "# Away mode\n"
     "\n"
     "Enter when the user says they're stepping away; leave when they return.\n"
     "\n"
     "## While away\n"
     "\n"
     "- Keep dispatching queued work and reconciling results as usual.\n"
     "- Hold anything needing a decision — checkpoints, failures wanting a\n"
     "  redispatch call, ambiguous intake — in a parked list (append task records\n"
     "  with status `paused` and a note) instead of asking.\n"
     "- Say nothing for routine completions; the log captures them.\n"
     "- Escalate only what can't wait (a worker destroying something, quota\n"
     "  exhausted, the whole queue blocked): one short spoken/sent line — over\n"
     "  relay or Telegram it reaches the phone automatically.\n"
     "\n"
     "## On return (\"I'm back\", or any new instruction)\n"
     "\n"
     "Recap before anything else: what finished, what failed, what's parked and\n"
     "needs their call — one sentence each, decisions last so they can answer in\n"
     "order.\n"
    },
    {"references/dispatch.md",
     "# Dispatch\n"
     "\n"
     "## Model selection\n"
     "\n"
     "Before every selection, run `~/.config/orchestrator/quota.sh` (real readings\n"
     "from mux's agenttabs cache, codex session logs as fallback) and re-anchor each\n"
     "backend it reports in usage.json: `remaining_pct`, `resets_at`, `read_at`,\n"
     "`source: \"rate_limit\"`, clearing drift. A null backend (grok has no quota\n"
     "source) keeps its last value; never treat an unread placeholder as full quota.\n"
     "\n"
     "Read routing.json for the task's class candidates and usage.json for quota.\n"
     "Projected remaining per backend = `remaining_pct` − Σ inflight `est` − the\n"
     "candidate's `est` (task_cost for that class, else routing seed_cost).\n"
     "Dispatch to the highest projected value; on dispatch, append the prediction\n"
     "to that backend's `inflight` and bump `dispatches`.\n"
     "\n"
     "## Spawning\n"
     "\n"
     "Workers are sibling sessions in this mux instance, spawned via the dispatch\n"
     "request file (src/dispatch.c in the mux repo):\n"
     "\n"
     "    printf '{\"backend\":\"claude\",\"model\":\"opus[1m]\",\"cwd\":\"<project cwd>\",\"prompt\":\"<worker prompt>\",\"title\":\"<task hash> <task short description>\"}' \\\n"
     "      > ~/.config/mux/dispatch/$MUX_PID-<task-id>.req\n"
     "\n"
     "The title is the worker's tab name; `<task hash>` is the task id without its\n"
     "`t-` prefix (e.g. `6beac7 deploy rmchores`).\n"
     "\n"
     "Poll for `$MUX_PID-<task-id>.res` (a few seconds); it holds the slot. The\n"
     "session id appears in the live registry (`~/.config/mux/live`) shortly after\n"
     "— record it in the task record. Delete the .res after reading.\n"
     "\n"
     "`{\"send\":\"<text>\",\"slot\":N}` types a message into a live worker's slot\n"
     "(reply `{\"ok\":true}` or `{\"error\": ...}`); used for follow-ups.\n"
     "\n"
     "The same directory takes `{\"close\":\"<session id>\"}` (or `{\"close\":<slot>}`)\n"
     "to close a tab; the reply is `{\"ok\":true,\"slot\":N,\"session\":\"<id>\"}` or\n"
     "`{\"error\": \"no such slot or session\" | \"slot is in view\" | \"slot is busy\"}`.\n"
     "\n"
     "For code tasks, first create a worktree `.claude/worktrees/<task-id>` (branch\n"
     "`worktree-<task-id>`) in the project repo and use it as cwd. Tasks whose deps\n"
     "are all done dispatch in parallel, each in its own worktree; never serialize\n"
     "independent tasks for lack of a commit — make the commit instead.\n"
     "\n"
     "## Worker prompt\n"
     "\n"
     "Always include: the task id and description; the project cwd; an instruction\n"
     "to read any spec files; scope limits (touch nothing outside scope, no\n"
     "commits unless the task says so); \"you are a worker — do not invoke the\n"
     "orchestrate skill or dispatch further workers\"; and the completion contract — \"as your\n"
     "final act write ~/.config/orchestrator/results/<task-id>.json per the result\n"
     "schema in this skill's references/schemas.md, with a one-paragraph\n"
     "summary sized for being read aloud.\"\n"
     "\n"
     "## Watcher\n"
     "\n"
     "After dispatching, start a background waiter on the result file(s) (a Bash\n"
     "run_in_background loop polling `~/.config/orchestrator/results/`, or fswatch\n"
     "if available) so completion re-invokes you without user prompting. Reconcile\n"
     "per references/monitor.md when it fires. Long dispatches also get a fallback\n"
     "heartbeat: if nothing has fired in ~20 minutes, reconcile anyway and probe\n"
     "anything overdue.\n"
     "\n"
     "## After spawning\n"
     "\n"
     "Append the task record update (status `dispatched`, backend, model, session,\n"
     "worktree) and a `dispatch` line to log.jsonl. Tell the user in one sentence\n"
     "who got the task.\n"
    },
    {"references/intake.md",
     "# Intake: plan → tasks\n"
     "\n"
     "For \"here's a plan for X\" or a spoken braindump.\n"
     "\n"
     "1. Resolve the project; read the plan (file, URL, or the transcript).\n"
     "2. Decompose into tasks that are independently dispatchable: one clear\n"
     "   deliverable each, small enough that a worker finishes in one session,\n"
     "   with deps for real ordering constraints only.\n"
     "3. Classify each: design/schema/architecture/review → `planning`; bug\n"
     "   hunting → `diagnosis`; everything else → `impl`. Mark natural user-review\n"
     "   points as checkpoint tasks.\n"
     "4. If the plan is large or ambiguous, run the decomposition on a\n"
     "   planning-class model (dispatch it like any task, with the plan text in\n"
     "   the prompt, asking for task records back as JSON) instead of doing it\n"
     "   inline.\n"
     "5. Append the records, then read back a compact summary: counts by class,\n"
     "   the first thing that would dispatch, and any checkpoint. Ask nothing\n"
     "   unless the plan genuinely forks.\n"
    },
    {"references/monitor.md",
     "# Monitoring\n"
     "\n"
     "## Reconcile (run on any status question, and each loop tick)\n"
     "\n"
     "1. Read new files in `~/.config/orchestrator/results/` — a task with\n"
     "   non-empty `pending` gets its follow-ups sent instead (tasks.md,\n"
     "   Follow-ups); for the rest, append the\n"
     "   task update (result `done` → task `review`, `failed` → `failed`, cost;\n"
     "   a task becomes `done` only once merged — see tasks.md), remove the backend's matching\n"
     "   `inflight` entry in usage.json and fold the observed spend into\n"
     "   `task_cost.est` (EMA, bump `n`), append a `result` log line.\n"
     "2. Scan `~/.config/mux/live` for recorded session ids: present = still\n"
     "   running; gone with no result file = suspect, note it. Finished worker\n"
     "   tabs stay open; close one only when the user asks.\n"
     "3. Dispatch any queued task whose deps just completed, unless the project is\n"
     "   paused on a checkpoint.\n"
     "\n"
     "## Restart reconcile\n"
     "\n"
     "The reconcile above is also the crash/restart recovery: state files are the\n"
     "only truth, so a fresh session that runs it resumes cleanly. Additionally:\n"
     "any usage.json `inflight` entry whose task has a result file gets folded in\n"
     "normally; one with no result and no live session is an orphan — mark the\n"
     "task `failed` with note \"lost across restart\" and tell the user. Re-start a\n"
     "background waiter for every task still `dispatched`.\n"
     "\n"
     "## Daily summary\n"
     "\n"
     "On the first interaction of a calendar day (compare the newest log.jsonl\n"
     "timestamp), open with one sentence from the last day's log — completions,\n"
     "failures, quota spent — before handling the request. Skip it if the log is\n"
     "empty.\n"
     "\n"
     "## Digests\n"
     "\n"
     "Speak only changes: finished, failed, newly stuck. One sentence per item,\n"
     "task description not id. Nothing changed → say nothing (loop tick) or \"all\n"
     "quiet, N still running\" (asked).\n"
     "\n"
     "## Probes\n"
     "\n"
     "For a worker running long with no result: fork its session read-only —\n"
     "`mux --session <id> --fork \"brief status: what are you doing and how far\n"
     "along?\"` — and relay a one-line summary. Log a `probe` line. Never probe more\n"
     "than once per task per ~10 minutes.\n"
     "\n"
     "## Stuck / failed\n"
     "\n"
     "A worker gone from the live dir without a result file, or a probe describing\n"
     "a loop: mark `failed` with a note, tell the user, and ask whether to\n"
     "redispatch (same or different backend) — redispatch costs quota, so it is\n"
     "the user's call.\n"
     "\n"
     "## Checkpoints\n"
     "\n"
     "When a checkpoint task completes: pause dispatching for that project, say\n"
     "what's ready to test, and wait. The reply's final sentence must be a concise\n"
     "test pointer: where the change lives and what to exercise. Feedback becomes\n"
     "new or amended task records; then resume.\n"
    },
    {"references/schemas.md",
     "# Orchestrator state: layout and schemas\n"
     "\n"
     "All state lives in `~/.config/orchestrator/`. Files are JSON or JSONL\n"
     "(append-only, one object per line, newest record per id wins — same\n"
     "convention as mux board.jsonl).\n"
     "Timestamps are unix epoch seconds. Ids are short random hex, prefixed by\n"
     "kind (`t-`, `r-`).\n"
     "\n"
     "## Layout\n"
     "\n"
     "    ~/.config/orchestrator/\n"
     "      registry.json        project name → cwd\n"
     "      routing.json         class → candidate backends, budgets\n"
     "      usage.json           per-backend quota estimate\n"
     "      projects/<name>.jsonl  task log per project\n"
     "      results/<task-id>.json result written by the worker\n"
     "      log.jsonl            dispatch/reconcile event log (debugging, digests)\n"
     "\n"
     "## registry.json\n"
     "\n"
     "    {\n"
     "      \"projects\": [\n"
     "        {\n"
     "          \"name\": \"mux\",\n"
     "          \"cwd\": \"/Users/jhickner/working/apps/mux\",\n"
     "          \"aliases\": [\"the repl\"]\n"
     "        }\n"
     "      ]\n"
     "    }\n"
     "\n"
     "Name resolution: exact name, then alias, case-insensitive.\n"
     "\n"
     "## Task record (projects/<name>.jsonl)\n"
     "\n"
     "    {\n"
     "      \"id\": \"t-3fa2c1\",\n"
     "      \"desc\": \"implement the project registry + name resolution\",\n"
     "      \"class\": \"planning\" | \"diagnosis\" | \"impl\",\n"
     "      \"status\": \"queued\" | \"dispatched\" | \"review\" | \"done\" | \"failed\" | \"paused\",\n"
     "      \"created\": 1757520000,\n"
     "      \"updated\": 1757523600,\n"
     "      \"deps\": [\"t-9b01aa\"],\n"
     "      \"checkpoint\": false,\n"
     "      \"backend\": \"claude\",        // set at dispatch\n"
     "      \"model\": \"opus[1m]\",\n"
     "      \"session\": \"<mux session id>\",\n"
     "      \"pid\": 12345,\n"
     "      \"worktree\": \".claude/worktrees/t-3fa2c1\",\n"
     "      \"cost_usd\": 0.42,\n"
     "      \"pending\": [\"follow-up tweak for the same worker\"],  // optional\n"
     "      \"notes\": \"free text: feedback, reassignments\"\n"
     "    }\n"
     "\n"
     "A status change appends a new full record with the same id. `review` means\n"
     "the worker finished and the change awaits user review and merge. `done` means\n"
     "complete and merged. `paused` marks a checkpoint hold. `deps` gates dispatch\n"
     "on other tasks being `done`. `pending` holds follow-up instructions queued for\n"
     "the task's live worker (tasks.md, Follow-ups).\n"
     "\n"
     "## Result file (results/<task-id>.json)\n"
     "\n"
     "Written by the worker as its final act; the injected system-prompt footer\n"
     "specifies path and shape. Presence of the file is the completion signal.\n"
     "\n"
     "    {\n"
     "      \"task\": \"t-3fa2c1\",\n"
     "      \"status\": \"done\" | \"failed\",\n"
     "      \"summary\": \"one paragraph, sized for TTS\",\n"
     "      \"files\": [\"src/registry.c\"],\n"
     "      \"commit\": \"abc1234\",          // optional\n"
     "      \"followups\": [\"suggested new task descriptions\"],  // optional\n"
     "      \"finished\": 1757523600\n"
     "    }\n"
     "\n"
     "## routing.json\n"
     "\n"
     "    {\n"
     "      \"classes\": {\n"
     "        \"planning\":  [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                      {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "        \"diagnosis\": [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                      {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "        \"impl\":      [{\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "                      {\"backend\": \"grok\", \"model\": \"grok-4.6\"},\n"
     "                      {\"backend\": \"codex\", \"model\": \"sol\"}]\n"
     "      },\n"
     "      \"orchestrator\": {\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "      \"seed_cost\": {\"planning\": 3, \"diagnosis\": 2, \"impl\": 5},\n"
     "      \"budgets\": {\"claude\": {\"max_pct_per_day\": 40}}\n"
     "    }\n"
     "\n"
     "Candidates within a class are equivalent; selection is quota-balanced (see\n"
     "usage.json). `seed_cost` is only the prior for a (backend, class) pair with\n"
     "no observations yet; learned estimates in usage.json take over from there.\n"
     "\n"
     "## usage.json\n"
     "\n"
     "    {\n"
     "      \"backends\": {\n"
     "        \"claude\": {\n"
     "          \"source\": \"rate_limit\" | \"cost\",\n"
     "          \"remaining_pct\": 51,        // last real reading, if any\n"
     "          \"read_at\": 1757520000,\n"
     "          \"cost_usd\": 3.10,\n"
     "          \"dispatches\": 4,\n"
     "          \"resets_at\": 1757534400,\n"
     "          \"task_cost\": {              // learned pct-per-task, by class\n"
     "            \"impl\":     {\"est\": 4.2, \"n\": 11},\n"
     "            \"planning\": {\"est\": 2.8, \"n\": 3}\n"
     "          },\n"
     "          \"inflight\": [               // predicted spend not yet observed\n"
     "            {\"task\": \"t-3fa2c1\", \"class\": \"impl\", \"est\": 4.2}\n"
     "          ]\n"
     "        },\n"
     "        \"grok\": { ... },\n"
     "        \"codex\": { ... }\n"
     "      }\n"
     "    }\n"
     "\n"
     "Selection: projected = `remaining_pct` − Σ inflight `est` − candidate's\n"
     "`est` (from `task_cost`, falling back to routing `seed_cost` when `n` is 0);\n"
     "dispatch to the backend with the highest projected value. On dispatch the\n"
     "prediction joins `inflight`; on completion it is removed and the observed\n"
     "quota delta (or cost-derived equivalent) updates `task_cost.est` as an\n"
     "exponential moving average and increments `n`. A fresh `rate_limit` reading\n"
     "re-anchors `remaining_pct` and clears any drift between predicted and real.\n"
     "\n"
     "## log.jsonl\n"
     "\n"
     "    {\"at\": 1757520000, \"ev\": \"dispatch\", \"task\": \"t-3fa2c1\",\n"
     "     \"backend\": \"claude\", \"detail\": \"...\"}\n"
     "\n"
     "Events: `dispatch`, `result`, `probe`, `stuck`, `checkpoint`, `reassign`,\n"
     "`error`. Source for spoken digests and the daily summary.\n"
    },
    {"references/stow.md",
     "# Stow\n"
     "\n"
     "Persist what this session learned; run when the user says \"stow\", at the end\n"
     "of a work stretch, or before a long away period.\n"
     "\n"
     "1. Durable knowledge — decisions made, constraints discovered, preferences\n"
     "   stated, gotchas hit — goes to `~/.config/orchestrator/notes/<project>.md`,\n"
     "   dated bullets, one line each. Facts the repo or ledger already records do\n"
     "   not belong there.\n"
     "2. Archive: move `done`/`failed` records older than ~7 days from\n"
     "   `projects/<name>.jsonl` to `projects/<name>.archive.jsonl` (newest record\n"
     "   per id, whole history for that id). Keep the live file small.\n"
     "3. Trim consumed result files for archived tasks into the archive dir.\n"
     "4. Confirm in one sentence: what was noted, how many records archived.\n"
    },
    {"references/tasks.md",
     "# Task operations\n"
     "\n"
     "Task records live in `~/.config/orchestrator/projects/<name>.jsonl`, one JSON\n"
     "object per line, append-only: a change is a new full record with the same id;\n"
     "the newest line per id is current. Schema: task record in\n"
     "references/schemas.md.\n"
     "\n"
     "## New project\n"
     "\n"
     "Create the directory under ~/working, `git init`, add a `.gitignore` for\n"
     "build output, and make an initial commit before any task is dispatched, so\n"
     "every code task can get its own worktree. Register it in registry.json. When\n"
     "a task in a new project completes, commit its files (explicit paths) so the\n"
     "next worktree branches from its work.\n"
     "\n"
     "## Add\n"
     "\n"
     "Resolve the project via registry.json. Generate id `t-` + 6 random hex.\n"
     "Append with class (infer: design/review/ambiguity → planning, bug hunting →\n"
     "diagnosis, everything else → impl), status `queued`, created/updated = now\n"
     "(unix seconds), deps [] unless the user names an ordering. Confirm in one\n"
     "sentence: task, project, class.\n"
     "\n"
     "## Dedupe\n"
     "\n"
     "Before appending, check the project's open (non-done) tasks for one covering\n"
     "the same work. If the new ask is a feature or tweak close to a `dispatched`\n"
     "task, don't ask and don't add a task: queue it as a follow-up (below). For\n"
     "any other likely match, say so and ask amend-or-new instead of adding a\n"
     "duplicate.\n"
     "\n"
     "## Follow-ups\n"
     "\n"
     "A follow-up goes to the task's existing worker, not through a separate task\n"
     "or review cycle. Append the task record with the instruction added to\n"
     "`pending` and confirm in one sentence. When that task's result arrives\n"
     "(monitor.md), don't move it to `review`: delete the result file, send the\n"
     "pending items to the worker's slot in one message via\n"
     "`{\"send\":\"<text>\",\"slot\":N}` (dispatch.md), restating the completion\n"
     "contract so it rewrites the result file, clear `pending`, keep status\n"
     "`dispatched`, restart the waiter, and log a `followup` line. The task reaches\n"
     "`review` once, after its last follow-up. If the worker's session is gone,\n"
     "dispatch the follow-up as a new task in the same worktree.\n"
     "\n"
     "## List / status\n"
     "\n"
     "Read the project file, collapse to newest-per-id, filter out `done` unless\n"
     "asked. Spoken form: count first, then the queued/dispatched few by short\n"
     "description — never read ids aloud. \"Three open in mux: the registry task is\n"
     "dispatched, two are queued.\"\n"
     "\n"
     "In mux, `/tasks` prints the open tasks across every orchestrator project as a\n"
     "grouped table with task, status, backend/model, and age. It also shows the live\n"
     "mux state of dispatched sessions. Use `/tasks all` to include done tasks.\n"
     "\n"
     "## Edit / complete / reassign\n"
     "\n"
     "Append a new record with the changed fields and updated timestamp. `done`\n"
     "means complete and merged, never just \"worker finished\" (that is `review`).\n"
     "When the user approves a `review` task: commit its worktree changes (explicit\n"
     "paths), merge the branch into the project's main branch, then set `done` with\n"
     "the merge commit in notes. Manual complete (user says it's done) sets status\n"
     "`done` and notes \"closed by user\".\n"
     "Reassign updates backend/model and appends a `reassign` line to log.jsonl.\n"
     "\n"
     "## Dependencies\n"
     "\n"
     "A task with unmet deps (any dep not `done`) is never dispatched; mention the\n"
     "blocker when listing it.\n"
    },
    {"references/update.md",
     "# Self-update\n"
     "\n"
     "When the user gives standing feedback on orchestrator behavior (\"from now\n"
     "on…\", \"always…\", \"stop doing…\"), change the skill itself, not just this\n"
     "session:\n"
     "\n"
     "1. Edit the matching file under `~/.claude/skills/orchestrate/` — the\n"
     "   contract for role/boundary changes, the reference for procedure changes.\n"
     "   Keep the contract thin; new procedures become reference sections, not\n"
     "   contract text.\n"
     "2. Append an `update` line to log.jsonl saying what changed and why.\n"
     "3. Confirm in one sentence. The change takes effect next skill load; note\n"
     "   that if it matters.\n"
     "\n"
     "Never weaken the hard rules (workers don't orchestrate, dispatch instead of\n"
     "implementing, TTS-sized replies) without the user saying so explicitly.\n"
    },
    {"routing.json",
     "{\n"
     "  \"classes\": {\n"
     "    \"planning\":  [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                  {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "    \"diagnosis\": [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                  {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "    \"impl\":      [{\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "                  {\"backend\": \"grok\", \"model\": \"grok-4.6\"},\n"
     "                  {\"backend\": \"codex\", \"model\": \"sol\"}]\n"
     "  },\n"
     "  \"orchestrator\": {\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "  \"seed_cost\": {\"planning\": 3, \"diagnosis\": 2, \"impl\": 5},\n"
     "  \"budgets\": {}\n"
     "}\n"
    },
};

const int orch_files_n = 11;
