#include "orchdata.h"

const struct orch_file orch_files[] = {
    {"SKILL.md",
     "---\n"
     "name: orchestrate\n"
     "description: Voice-first task orchestrator over mux. Use when the user adds, lists, dispatches, or asks status of project tasks (\"add a task to mux\", \"what's queued\", \"dispatch it\", \"how's the auth task going\", \"here's a plan for X\"), or says /orchestrate. Not for dispatched workers: a session whose prompt names it a dispatched worker must never invoke this skill.\n"
     "---\n"
     "\n"
     "# orchestrate\n"
     "\n"
     "You are the orchestrator: one session that stays free for instruction and\n"
     "delegates all nontrivial work.\n"
     "\n"
     "The bookkeeping is not yours. mux runs the orchestrator as a subsystem, the\n"
     "same way it runs the relay and Telegram: it owns `~/.config/orchestrator`,\n"
     "watches the workers, folds in results, and tells you when something happened.\n"
     "You do the parts that need judgement — what the work is, how to split it, who\n"
     "should do it, what to say about it — and you drive the subsystem through\n"
     "`mux orch`. Never hand-edit the state files; the subsystem writes them under a\n"
     "lock, and a second writer is how records get lost.\n"
     "\n"
     "Classify delegated work before dispatching it:\n"
     "\n"
     "- Create an orchestrator project task only for user-requested product work:\n"
     "  features, bug fixes, implementation changes, or another durable deliverable.\n"
     "- For ad-hoc research, credential lookup, status investigation, and other\n"
     "  non-product multi-step work, dispatch a one-off subagent without creating a\n"
     "  project task record.\n"
     "\n"
     "A request may run inline only when it needs no tools, exactly one trivial read,\n"
     "or exactly one trivial shell command. Investigation, code edits, testing,\n"
     "installs, merges, deploys, and all other multi-step operations are delegated.\n"
     "This limit does not apply to `mux orch` calls. Keep every reply sized for TTS:\n"
     "one or two sentences unless asked for a full readout.\n"
     "\n"
     "## The subsystem\n"
     "\n"
     "One mux instance runs the orchestrator, claimed by `--orchestrator` or\n"
     "`/orchestrator` and held by that instance until it exits. `mux orch` works from\n"
     "any terminal: reads and plain state changes run in place, and the verbs that\n"
     "need a live mux say so plainly when no instance has it.\n"
     "\n"
     "    mux orch list [all] [--json]      open tasks, or every task\n"
     "    mux orch show <task>              one task, in full, with its live state\n"
     "    mux orch projects                 known projects and their directories\n"
     "    mux orch add <project> <text>     a new queued task\n"
     "    mux orch status <task> <status>   move it\n"
     "    mux orch note <task> <text>       append to its notes\n"
     "    mux orch followup <task> <text>   queue an instruction for its worker\n"
     "    mux orch dispatch <task> <prompt> start a worker\n"
     "    mux orch send <task> <text>       type at its live worker\n"
     "    mux orch reconcile                fold in results now\n"
     "\n"
     "If a verb reports that no instance is running the orchestrator, say so and ask\n"
     "the user to start one; do not fall back to editing the files by hand.\n"
     "\n"
     "## State\n"
     "\n"
     "All state is in `~/.config/orchestrator/`, and the subsystem is its writer.\n"
     "Schemas: references/schemas.md next to this skill.\n"
     "\n"
     "- `registry.json` — project name → cwd. Name resolution happens inside\n"
     "  `mux orch`: pass what the user said. If nothing resolves, ask, then add the\n"
     "  name or alias to the registry.\n"
     "- `projects/<name>.jsonl` — append-only task log, newest record per id wins.\n"
     "- `results/<task-id>.json` — worker-written completion signal.\n"
     "- `events/` — completions waiting to be delivered. Not yours to touch.\n"
     "- `routing.json`, `usage.json` — class → models, quota estimates.\n"
     "- `log.jsonl` — event log for digests.\n"
     "\n"
     "## Routing index\n"
     "\n"
     "Load the matching reference only when its situation arises:\n"
     "\n"
     "- Adding, listing, editing, completing tasks → `references/tasks.md`\n"
     "- Turning a plan or a spoken braindump into tasks → `references/intake.md`\n"
     "- Dispatching work to a worker session → `references/dispatch.md`\n"
     "- Checking on workers, digests, probes, checkpoints → `references/monitor.md`\n"
     "- User stepping away or returning → `references/afk.md`\n"
     "- Persisting learned knowledge, archiving old records → `references/stow.md`\n"
     "- Standing feedback on orchestrator behavior → `references/update.md`\n"
     "\n"
     "## Rules\n"
     "\n"
     "- Do not start a background waiter, a polling loop, or a heartbeat. The\n"
     "  subsystem watches the workers and sends you a line when one finishes or dies,\n"
     "  and reconciles on its own besides. A message that begins \"orchestrator:\" is\n"
     "  that mechanism talking to you: act on it and tell the user.\n"
     "- Task classes: `planning`, `diagnosis`, `impl`. Class decides the model per\n"
     "  routing.json.\n"
     "- Answer status questions from `mux orch list` and `mux orch show` first; only\n"
     "  probe a worker when those can't answer.\n"
     "- Checkpoint tasks pause the project's dispatching until the user reviews.\n"
    },
    {"quota.sh",
     "#!/usr/bin/env bash\n"
     "# Read-only real quota snapshot for claude/codex/grok. Prints one JSON object:\n"
     "#   {backend: {remaining_pct, resets_at, read_at, source}}\n"
     "# remaining_pct/resets_at are null when no reading is available.\n"
     "#\n"
     "# Sources:\n"
     "#   claude/codex/grok: mux's agenttabs state dir, written by claude.h/codex.h/grok.h\n"
     "#                 rate_limit hooks whenever mux runs those backends. Falls back to\n"
     "#                 scanning codex CLI session jsonl (~/.codex/sessions) for codex only.\n"
     "set -euo pipefail\n"
     "\n"
     "now=$(date +%s)\n"
     "\n"
     "state_dir() {\n"
     "    if [ -n \"${AGENT_TABS_STATE_DIR:-}\" ]; then\n"
     "        echo \"$AGENT_TABS_STATE_DIR\"\n"
     "        return\n"
     "    fi\n"
     "    local base=\"$HOME/.config/tmux\"\n"
     "    local legacy=\"$HOME/.tmux\"\n"
     "    if [ ! -d \"$base\" ] && [ -d \"$legacy\" ]; then\n"
     "        base=\"$legacy\"\n"
     "    fi\n"
     "    echo \"$base/tmux-agent-tabs\"\n"
     "}\n"
     "\n"
     "agents_dir=\"$(state_dir)/agents\"\n"
     "\n"
     "# Latest usage reading for one backend name from mux's agent-tab records.\n"
     "# Emits {remaining_pct, resets_at, read_at, source} or \"null\".\n"
     "latest_from_agenttabs() {\n"
     "    local backend=\"$1\"\n"
     "    [ -d \"$agents_dir\" ] || { echo \"null\"; return; }\n"
     "    jq -s --arg backend \"$backend\" --arg src \"mux agenttabs: $agents_dir\" '\n"
     "        map(select(.agent == $backend and (.usage_percent != null)))\n"
     "        | sort_by(.usage_ts) | last\n"
     "        | if . == null then null else {\n"
     "            remaining_pct: (100 - .usage_percent),\n"
     "            resets_at: .usage_resets_at,\n"
     "            read_at: .usage_ts,\n"
     "            source: $src\n"
     "          } end\n"
     "    ' \"$agents_dir\"/*.json 2>/dev/null || echo \"null\"\n"
     "}\n"
     "\n"
     "# Fallback for codex: scan recent session jsonl files for the latest\n"
     "# token_count event's rate_limits.primary block.\n"
     "latest_from_codex_sessions() {\n"
     "    local sessions_dir=\"$HOME/.codex/sessions\"\n"
     "    [ -d \"$sessions_dir\" ] || { echo \"null\"; return; }\n"
     "    local f\n"
     "    f=$(find \"$sessions_dir\" -iname '*.jsonl' -newermt '-7 days' -print0 2>/dev/null \\\n"
     "        | xargs -0 ls -t 2>/dev/null | head -1)\n"
     "    [ -n \"$f\" ] || { echo \"null\"; return; }\n"
     "    /usr/bin/grep '\"rate_limits\"' \"$f\" 2>/dev/null | tail -1 | jq --arg src \"codex session jsonl: $f\" '\n"
     "        .payload.rate_limits.primary as $p\n"
     "        | if $p == null then null else {\n"
     "            remaining_pct: (100 - $p.used_percent),\n"
     "            resets_at: $p.resets_at,\n"
     "            read_at: (.timestamp | fromdateiso8601),\n"
     "            source: $src\n"
     "          } end\n"
     "    ' 2>/dev/null || echo \"null\"\n"
     "}\n"
     "\n"
     "claude=$(latest_from_agenttabs claude)\n"
     "codex=$(latest_from_agenttabs codex)\n"
     "if [ \"$codex\" = \"null\" ]; then\n"
     "    codex=$(latest_from_codex_sessions)\n"
     "fi\n"
     "grok=$(latest_from_agenttabs grok)\n"
     "\n"
     "jq -n --argjson claude \"$claude\" --argjson codex \"$codex\" --argjson grok \"$grok\" \\\n"
     "    '{claude: $claude, codex: $codex, grok: $grok}'\n"
    },
    {"references/afk.md",
     "# Away mode\n"
     "\n"
     "Enter when the user says they're stepping away; leave when they return.\n"
     "\n"
     "## While away\n"
     "\n"
     "- Keep dispatching queued work as usual; the subsystem keeps reconciling\n"
     "  whether or not you are mid-conversation.\n"
     "- Hold anything needing a decision — checkpoints, failures wanting a\n"
     "  redispatch call, ambiguous intake — in a parked list (append task records\n"
     "  with status `paused` and a note) instead of asking.\n"
     "- Say nothing for routine completions; the log captures them.\n"
     "- Escalate only what can't wait (a worker destroying something, quota\n"
     "  exhausted, the whole queue blocked): one short spoken/sent line — over\n"
     "  relay or Telegram it reaches the phone automatically.\n"
     "\n"
     "## On return (\"I'm back\", or any new instruction)\n"
     "\n"
     "Recap before anything else: what finished, what failed, what's parked and\n"
     "needs their call — one sentence each, decisions last so they can answer in\n"
     "order.\n"
    },
    {"references/dispatch.md",
     "# Dispatch\n"
     "\n"
     "## Model selection\n"
     "\n"
     "Before every selection, run `~/.config/orchestrator/quota.sh` (real readings\n"
     "from mux's agenttabs cache, codex session logs as fallback) and re-anchor each\n"
     "backend it reports in usage.json: `remaining_pct`, `resets_at`, `read_at`,\n"
     "`source: \"rate_limit\"`, clearing drift. A null backend (grok has no quota\n"
     "source) keeps its last value; never treat an unread placeholder as full quota.\n"
     "\n"
     "Read routing.json for the task's class candidates and usage.json for quota.\n"
     "For a one-off, infer the closest class for routing only; this does not create a\n"
     "project task. Projected remaining per backend = `remaining_pct` − Σ inflight\n"
     "`est` − the candidate's `est` (task_cost for that class, else routing\n"
     "seed_cost). Dispatch to the highest projected value; on dispatch, append the\n"
     "prediction to that backend's `inflight` and bump `dispatches`.\n"
     "\n"
     "## Dispatching a project task\n"
     "\n"
     "    mux orch dispatch <task-id> \"<worker prompt>\" \\\n"
     "      --backend claude --model \"opus[1m]\" --cwd <worktree> --title \"<hash> <short desc>\"\n"
     "\n"
     "That one call does the mechanical part: it picks the instance, writes the\n"
     "worker request, waits for the session id, records backend, model, session and\n"
     "instance on the task, moves it to `dispatched`, logs the dispatch, and arms the\n"
     "completion notification. It answers with the task, the session id and the pid,\n"
     "or with an error and no state change.\n"
     "\n"
     "Instance choice is not yours either: the task's origin instance is preferred,\n"
     "then the most recently active instance with a free tab. If no instance has\n"
     "room, the dispatch is refused and the task stays queued — say so and move on\n"
     "rather than forcing it somewhere.\n"
     "\n"
     "A task that is already `dispatched` with a live worker is refused. That is\n"
     "deliberate: two workers on one task have collided in the same worktree before.\n"
     "To redirect live work, send a follow-up instead.\n"
     "\n"
     "For code tasks, create the worktree first — `.claude/worktrees/<task-id>`,\n"
     "branch `worktree-<task-id>` — and pass it as `--cwd`. Tasks whose deps are all\n"
     "done dispatch in parallel, each in its own worktree; never serialize\n"
     "independent tasks for lack of a commit, make the commit instead.\n"
     "\n"
     "## Follow-ups\n"
     "\n"
     "`mux orch send <task> \"<text>\"` types at the task's live worker. If the worker\n"
     "is gone, the text is queued on the task instead and the reply says so.\n"
     "\n"
     "## One-off non-product work\n"
     "\n"
     "Ad-hoc research, credential lookup, status investigation, and other non-product\n"
     "multi-step requests go to a one-off subagent, spawned directly through mux's\n"
     "own dispatch directory rather than through `mux orch`:\n"
     "\n"
     "    printf '{\"backend\":\"claude\",\"model\":\"opus[1m]\",\"cwd\":\"<cwd>\",\"prompt\":\"<prompt>\",\"title\":\"<short desc>\"}' \\\n"
     "      > ~/.config/mux/dispatch/$MUX_PID-<o-key>.req\n"
     "\n"
     "Poll for `$MUX_PID-<o-key>.res`; mux holds that reply until the backend reports\n"
     "its session id, up to 30 seconds, then answers `{\"session\":\"<id>\",\"addr\":\"<path>\"}`.\n"
     "`{\"error\":\"session id unavailable\"}` means the worker is unaddressable — treat\n"
     "the dispatch as failed. Delete the .res after reading. Do not create a project\n"
     "task record, a worktree, or a lifecycle for a one-off. Its prompt must write a\n"
     "transient result to `~/.config/orchestrator/results/<o-key>.json` using the\n"
     "one-off result schema in schemas.md; read it, report it, delete it.\n"
     "\n"
     "A session id is the only address the dispatch API accepts; there is no\n"
     "positional addressing. `{\"send\":...}` and `{\"close\":...}` take one too.\n"
     "\n"
     "## Worker prompt\n"
     "\n"
     "For a project task, always include: the task id and description; the project\n"
     "cwd; an instruction to read any spec files; scope limits (touch nothing outside\n"
     "scope, no commits unless the task says so); \"you are a worker — do not invoke\n"
     "the orchestrate skill or dispatch further workers\"; and the completion contract\n"
     "— \"as your final act write `~/.config/orchestrator/results/<task-id>.json` per\n"
     "the result schema in this skill's references/schemas.md, with a one-paragraph\n"
     "summary sized for being read aloud.\"\n"
     "\n"
     "A worker can name its own session: `$MUX_SESSION_FILE` holds the path of a file\n"
     "containing its session id, once the backend has reported one. Tell a worker\n"
     "about it only when the work needs it.\n"
     "\n"
     "For a one-off, include the request and relevant cwd, prohibit product changes,\n"
     "commits, and further dispatch, identify it as a one-off subagent rather than a\n"
     "project task, and include the transient completion contract above.\n"
     "\n"
     "## No watcher\n"
     "\n"
     "Do not start a background waiter, an fswatch, or a polling loop. The instance\n"
     "hosting the worker records its ending — finished turn or death — and the\n"
     "orchestrator subsystem delivers that to you as a line beginning\n"
     "\"orchestrator:\", then reconciles. A completion that is somehow missed is picked\n"
     "up by the periodic reconcile, which runs about every twenty minutes\n"
     "(`orchestrator_reconcile_minutes` in mux settings) and on every start.\n"
     "\n"
     "## After dispatching\n"
     "\n"
     "Tell the user in one sentence who got the request. The task record and the log\n"
     "line are already written.\n"
    },
    {"references/intake.md",
     "# Intake: plan → tasks\n"
     "\n"
     "For \"here's a plan for X\" or a spoken braindump.\n"
     "\n"
     "1. Resolve the project; read the plan (file, URL, or the transcript).\n"
     "2. Decompose into tasks that are independently dispatchable: one clear\n"
     "   deliverable each, small enough that a worker finishes in one session,\n"
     "   with deps for real ordering constraints only.\n"
     "3. Classify each: design/schema/architecture/review → `planning`; bug\n"
     "   hunting → `diagnosis`; everything else → `impl`. Mark natural user-review\n"
     "   points as checkpoint tasks.\n"
     "4. If the plan is large or ambiguous, run the decomposition on a\n"
     "   planning-class model (dispatch it like any task, with the plan text in\n"
     "   the prompt, asking for task records back as JSON) instead of doing it\n"
     "   inline.\n"
     "5. Add the records with `mux orch add`, then read back a compact summary:\n"
     "   counts by class, the first thing that would dispatch, and any checkpoint.\n"
     "   Ask nothing unless the plan genuinely forks.\n"
    },
    {"references/monitor.md",
     "# Monitoring\n"
     "\n"
     "## Who does what\n"
     "\n"
     "The subsystem folds in results, notices dead workers and keeps the task records\n"
     "straight. You read the outcome and say something useful about it. When a line\n"
     "arriving in your session begins \"orchestrator:\", that is the subsystem: it has\n"
     "already moved the record, so do not move it again — read the state, tell the\n"
     "user, and decide what happens next.\n"
     "\n"
     "## Reconcile\n"
     "\n"
     "`mux orch reconcile` runs it on demand; the subsystem also runs it on start and\n"
     "on a timer. One pass does:\n"
     "\n"
     "1. Every open task with a result file: `done` → `review`, anything else →\n"
     "   `failed`, the result file consumed, a `result` line logged.\n"
     "2. Every `dispatched` task whose session is gone from `~/.config/mux/live` with\n"
     "   no result: `failed`, noted \"worker ended without writing a result\".\n"
     "3. You are told about each one.\n"
     "\n"
     "After a reconcile, fold the quota side in yourself: remove the backend's\n"
     "matching `inflight` entry in usage.json and fold the observed spend into\n"
     "`task_cost.est` (EMA, bump `n`).\n"
     "\n"
     "A task with queued follow-ups (`pending` non-empty) that reports a result is\n"
     "not finished: send the follow-ups with `mux orch send`, restating the\n"
     "completion contract so the worker rewrites its result file, and leave the task\n"
     "`dispatched`. It reaches `review` after its last follow-up.\n"
     "\n"
     "Then dispatch any queued task whose deps just completed, unless the project is\n"
     "paused on a checkpoint.\n"
     "\n"
     "## Restart\n"
     "\n"
     "State files are the truth and reconcile is the recovery: a fresh orchestrator\n"
     "session, or a fresh mux, resumes by running it. Completion events are files\n"
     "too, so anything that finished while nothing was listening is delivered once\n"
     "something is. Any usage.json `inflight` entry whose task has no result and no\n"
     "live session is an orphan: fold it out and say so.\n"
     "\n"
     "## Daily summary\n"
     "\n"
     "On the first interaction of a calendar day (compare the newest log.jsonl\n"
     "timestamp), open with one sentence from the last day's log — completions,\n"
     "failures, quota spent — before handling the request. Skip it if the log is\n"
     "empty.\n"
     "\n"
     "## Digests\n"
     "\n"
     "Speak only changes: finished, failed, newly stuck. One sentence per item, task\n"
     "description not id. Nothing changed → say nothing (a notification you have\n"
     "already reported) or \"all quiet, N still running\" (asked).\n"
     "\n"
     "## Probes\n"
     "\n"
     "For a worker running long with no result: fork its session read-only —\n"
     "`mux --session <id> --fork \"brief status: what are you doing and how far\n"
     "along?\"` — and relay a one-line summary. Log a `probe` line. Never probe more\n"
     "than once per task per ~10 minutes.\n"
     "\n"
     "## Stuck / failed\n"
     "\n"
     "A worker the subsystem marked failed, or a probe describing a loop: tell the\n"
     "user and ask whether to redispatch (same or different backend) — redispatch\n"
     "costs quota, so it is the user's call.\n"
     "\n"
     "## Checkpoints\n"
     "\n"
     "When a checkpoint task completes: pause dispatching for that project, say\n"
     "what's ready to test, and wait. The reply's final sentence must be a concise\n"
     "test pointer: where the change lives and what to exercise. Feedback becomes new\n"
     "or amended task records; then resume.\n"
    },
    {"references/schemas.md",
     "# Orchestrator state: layout and schemas\n"
     "\n"
     "All state lives in `~/.config/orchestrator/`. Files are JSON or JSONL\n"
     "(append-only, one object per line, newest record per id wins — same\n"
     "convention as mux board.jsonl).\n"
     "Timestamps are unix epoch seconds. Persistent ids are short random hex,\n"
     "prefixed by kind (`t-`, `r-`). Transient one-off request keys use `o-`.\n"
     "\n"
     "## Layout\n"
     "\n"
     "    ~/.config/orchestrator/\n"
     "      registry.json        project name → cwd\n"
     "      routing.json         class → candidate backends, budgets\n"
     "      usage.json           per-backend quota estimate\n"
     "      projects/<name>.jsonl  task log per project\n"
     "      results/<task-id>.json result written by a project worker\n"
     "      results/<one-off-key>.json transient result written by a one-off subagent\n"
     "      events/              completion events waiting to be delivered, written by\n"
     "                           the instance hosting a worker and drained by the\n"
     "                           instance running the orchestrator\n"
     "      requests/            `mux orch` request and reply files\n"
     "      log.jsonl            project dispatch/reconcile log (debugging, digests)\n"
     "\n"
     "Everything here is written by the mux orchestrator subsystem, under a lock per\n"
     "file. Read them freely; write them through `mux orch`.\n"
     "\n"
     "## registry.json\n"
     "\n"
     "    {\n"
     "      \"projects\": [\n"
     "        {\n"
     "          \"name\": \"mux\",\n"
     "          \"cwd\": \"/Users/jhickner/working/apps/mux\",\n"
     "          \"aliases\": [\"the repl\"]\n"
     "        }\n"
     "      ]\n"
     "    }\n"
     "\n"
     "Name resolution: exact name, then alias, case-insensitive.\n"
     "\n"
     "## Task record (projects/<name>.jsonl)\n"
     "\n"
     "    {\n"
     "      \"id\": \"t-3fa2c1\",\n"
     "      \"desc\": \"implement the project registry + name resolution\",\n"
     "      \"class\": \"planning\" | \"diagnosis\" | \"impl\",\n"
     "      \"status\": \"queued\" | \"dispatched\" | \"review\" | \"done\" | \"failed\" |\n"
     "                \"paused\" | \"cancelled\",\n"
     "      \"created\": 1757520000,\n"
     "      \"updated\": 1757523600,\n"
     "      \"deps\": [\"t-9b01aa\"],\n"
     "      \"checkpoint\": false,\n"
     "      \"backend\": \"claude\",        // set at dispatch\n"
     "      \"model\": \"opus[1m]\",\n"
     "      \"session\": \"<mux session id>\",\n"
     "      \"pid\": 12345,                 // the instance the work belongs to: set at\n"
     "                                    // creation as the origin, and again at\n"
     "                                    // dispatch as the host\n"
     "      \"worktree\": \".claude/worktrees/t-3fa2c1\",\n"
     "      \"cost_usd\": 0.42,\n"
     "      \"pending\": [\"follow-up tweak for the same worker\"],  // optional\n"
     "      \"notes\": \"free text: feedback, reassignments\"\n"
     "    }\n"
     "\n"
     "A status change appends a new full record with the same id. `review` means\n"
     "the worker finished and the change awaits user review and merge. `done` means\n"
     "complete and merged, and is terminal: nothing moves out of it. `cancelled`\n"
     "means abandoned; it leaves the open list like `done` but can be reopened.\n"
     "`paused` marks a checkpoint hold. `deps` gates dispatch on other tasks being\n"
     "`done`. `pending` holds follow-up instructions queued for the task's live\n"
     "worker (tasks.md, Follow-ups).\n"
     "\n"
     "## Result file (results/<task-id>.json)\n"
     "\n"
     "Written by the worker as its final act; the injected system-prompt footer\n"
     "specifies path and shape. Presence of the file is the completion signal.\n"
     "\n"
     "    {\n"
     "      \"task\": \"t-3fa2c1\",\n"
     "      \"status\": \"done\" | \"failed\",\n"
     "      \"summary\": \"one paragraph, sized for TTS\",\n"
     "      \"files\": [\"src/registry.c\"],\n"
     "      \"commit\": \"abc1234\",          // optional\n"
     "      \"followups\": [\"suggested new task descriptions\"],  // optional\n"
     "      \"finished\": 1757523600\n"
     "    }\n"
     "\n"
     "## One-off result (results/<one-off-key>.json)\n"
     "\n"
     "A one-off subagent writes this as its final act. It is a transient completion\n"
     "signal, not a project task record; read and delete it without appending a task\n"
     "or task lifecycle event.\n"
     "\n"
     "    {\n"
     "      \"one_off\": \"o-4bc921\",\n"
     "      \"status\": \"done\" | \"failed\",\n"
     "      \"summary\": \"the requested finding, sized for TTS\",\n"
     "      \"finished\": 1757523600\n"
     "    }\n"
     "\n"
     "## Completion event (events/<name>.json)\n"
     "\n"
     "Written by the instance hosting a worker when that worker finishes a turn or\n"
     "ends, and deleted by the orchestrator once it has been delivered. Not a\n"
     "completion in itself: the result file is still the signal, and a lost event\n"
     "costs nothing but time, since reconcile finds the same thing.\n"
     "\n"
     "    {\n"
     "      \"task\": \"t-3fa2c1\",\n"
     "      \"session\": \"<the worker's session id>\",\n"
     "      \"notify\": \"<who asked to be told>\",\n"
     "      \"reason\": \"idle\" | \"exit\",\n"
     "      \"ts\": 1757523600\n"
     "    }\n"
     "\n"
     "## routing.json\n"
     "\n"
     "    {\n"
     "      \"classes\": {\n"
     "        \"planning\":  [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                      {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "        \"diagnosis\": [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                      {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "        \"impl\":      [{\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "                      {\"backend\": \"grok\", \"model\": \"grok-4.6\"},\n"
     "                      {\"backend\": \"codex\", \"model\": \"sol\"}]\n"
     "      },\n"
     "      \"orchestrator\": {\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "      \"seed_cost\": {\"planning\": 3, \"diagnosis\": 2, \"impl\": 5},\n"
     "      \"budgets\": {\"claude\": {\"max_pct_per_day\": 40}}\n"
     "    }\n"
     "\n"
     "Candidates within a class are equivalent; selection is quota-balanced (see\n"
     "usage.json). `seed_cost` is only the prior for a (backend, class) pair with\n"
     "no observations yet; learned estimates in usage.json take over from there.\n"
     "\n"
     "## usage.json\n"
     "\n"
     "    {\n"
     "      \"backends\": {\n"
     "        \"claude\": {\n"
     "          \"source\": \"rate_limit\" | \"cost\",\n"
     "          \"remaining_pct\": 51,        // last real reading, if any\n"
     "          \"read_at\": 1757520000,\n"
     "          \"cost_usd\": 3.10,\n"
     "          \"dispatches\": 4,\n"
     "          \"resets_at\": 1757534400,\n"
     "          \"task_cost\": {              // learned pct-per-task, by class\n"
     "            \"impl\":     {\"est\": 4.2, \"n\": 11},\n"
     "            \"planning\": {\"est\": 2.8, \"n\": 3}\n"
     "          },\n"
     "          \"inflight\": [               // predicted spend not yet observed\n"
     "            {\"task\": \"t-3fa2c1\", \"class\": \"impl\", \"est\": 4.2}\n"
     "          ]\n"
     "        },\n"
     "        \"grok\": { ... },\n"
     "        \"codex\": { ... }\n"
     "      }\n"
     "    }\n"
     "\n"
     "Selection: projected = `remaining_pct` − Σ inflight `est` − candidate's\n"
     "`est` (from `task_cost`, falling back to routing `seed_cost` when `n` is 0);\n"
     "dispatch to the backend with the highest projected value. On dispatch the\n"
     "prediction joins `inflight`; on completion it is removed and the observed\n"
     "quota delta (or cost-derived equivalent) updates `task_cost.est` as an\n"
     "exponential moving average and increments `n`. A fresh `rate_limit` reading\n"
     "re-anchors `remaining_pct` and clears any drift between predicted and real.\n"
     "\n"
     "## log.jsonl\n"
     "\n"
     "    {\"at\": 1757520000, \"ev\": \"dispatch\", \"task\": \"t-3fa2c1\",\n"
     "     \"backend\": \"claude\", \"detail\": \"...\"}\n"
     "\n"
     "Events: `dispatch`, `result`, `probe`, `stuck`, `checkpoint`, `reassign`,\n"
     "`error`. Source for spoken digests and the daily summary.\n"
    },
    {"references/stow.md",
     "# Stow\n"
     "\n"
     "Persist what this session learned; run when the user says \"stow\", at the end\n"
     "of a work stretch, or before a long away period.\n"
     "\n"
     "1. Durable knowledge — decisions made, constraints discovered, preferences\n"
     "   stated, gotchas hit — goes to `~/.config/orchestrator/notes/<project>.md`,\n"
     "   dated bullets, one line each. Facts the repo or ledger already records do\n"
     "   not belong there.\n"
     "2. Archive: move `done`/`cancelled`/`failed` records older than ~7 days from\n"
     "   `projects/<name>.jsonl` to `projects/<name>.archive.jsonl` (newest record\n"
     "   per id, whole history for that id). Keep the live file small.\n"
     "3. Trim consumed result files for archived tasks into the archive dir.\n"
     "4. Confirm in one sentence: what was noted, how many records archived.\n"
    },
    {"references/tasks.md",
     "# Task operations\n"
     "\n"
     "Task records live in `~/.config/orchestrator/projects/<name>.jsonl`, one JSON\n"
     "object per line, append-only: a change is a new full record with the same id;\n"
     "the newest line per id is current. Schema: task record in\n"
     "references/schemas.md. `mux orch` is the only writer — it takes the file lock,\n"
     "carries every field forward, and appends. Reach for an editor only to repair\n"
     "something the tool cannot express, and say so when you do.\n"
     "\n"
     "## Scope\n"
     "\n"
     "Create records here only for user-requested product work: features, bug fixes,\n"
     "implementation changes, or another durable deliverable. Ad-hoc research,\n"
     "credential lookup, status investigation, and other non-product multi-step work\n"
     "are not project tasks; delegate them as one-off subagents per dispatch.md.\n"
     "\n"
     "## New project\n"
     "\n"
     "Create and dispatch a task to make the directory under ~/working, run `git\n"
     "init`, add a `.gitignore` for build output, and make an initial commit. Once it\n"
     "completes, register the project in registry.json; do not perform project setup\n"
     "inline. Later code tasks can then get their own worktrees. When a task in a new\n"
     "project completes, have a worker commit its explicit files so the next worktree\n"
     "branches from its work.\n"
     "\n"
     "## Add\n"
     "\n"
     "    mux orch add <project> \"<description>\" --class <planning|diagnosis|impl> [--checkpoint]\n"
     "\n"
     "The project is whatever the user said: name or alias, case-insensitive. Infer\n"
     "the class — design/review/ambiguity → planning, product bug hunting →\n"
     "diagnosis, everything else → impl. The call answers with the new id. Confirm in\n"
     "one sentence: task, project, class.\n"
     "\n"
     "## Dedupe\n"
     "\n"
     "Before adding, read `mux orch list` for one covering the same work. If the new\n"
     "ask is a feature or tweak close to a `dispatched` task, don't ask and don't add\n"
     "a task: queue it as a follow-up. For any other likely match, say so and ask\n"
     "amend-or-new instead of adding a duplicate.\n"
     "\n"
     "## Follow-ups\n"
     "\n"
     "A follow-up goes to the task's existing worker, not through a separate task or\n"
     "review cycle.\n"
     "\n"
     "    mux orch send <task> \"<instruction>\"\n"
     "\n"
     "If the worker is live it is typed at it; if not, it is queued on the task and\n"
     "the reply says `queued`. Restate the completion contract when a follow-up\n"
     "lands, so the worker rewrites its result file. Keep the task `dispatched`; it\n"
     "reaches `review` once, after its last follow-up. If the worker's session is\n"
     "gone for good, dispatch the follow-up as a new task in the same worktree.\n"
     "\n"
     "## List / status\n"
     "\n"
     "    mux orch list          open tasks across every project\n"
     "    mux orch list all      including done and cancelled\n"
     "    mux orch show <task>   one task in full, plus its live session state\n"
     "\n"
     "Spoken form: count first, then the queued/dispatched few by short description —\n"
     "never read ids aloud. \"Three open in mux: the registry task is dispatched, two\n"
     "are queued.\"\n"
     "\n"
     "Inside mux, `/tasks` prints the same open tasks as a grouped table with task,\n"
     "id, status, backend/model and age, and shows the live state of dispatched\n"
     "sessions. `/tasks all` includes the closed ones.\n"
     "\n"
     "## Edit / complete / cancel\n"
     "\n"
     "    mux orch status <task> <status>\n"
     "    mux orch note <task> \"<text>\"\n"
     "\n"
     "`review` means the worker finished and the change awaits review and merge.\n"
     "`done` means complete and merged, and nothing moves out of `done`. When the\n"
     "user approves a `review` task, dispatch a worker to commit its worktree changes\n"
     "(explicit paths) and merge the branch into the project's main branch, then set\n"
     "`done` with the merge commit in notes. Manual complete (user says it's done)\n"
     "sets `done` and notes \"closed by user\". `cancelled` is for work that will never\n"
     "be done; like `done` it drops out of the open list, but unlike `done` it can be\n"
     "reopened. Reassignment is a dispatch with a different backend or model.\n"
     "\n"
     "## Dependencies\n"
     "\n"
     "A task with unmet deps (any dep not `done`) is never dispatched; mention the\n"
     "blocker when listing it.\n"
    },
    {"references/update.md",
     "# Self-update\n"
     "\n"
     "When the user gives standing feedback on orchestrator behavior (\"from now\n"
     "on…\", \"always…\", \"stop doing…\"), change the skill itself, not just this\n"
     "session:\n"
     "\n"
     "1. Edit the matching file under `~/.claude/skills/orchestrate/` — the\n"
     "   contract for role/boundary changes, the reference for procedure changes.\n"
     "   Keep the contract thin; new procedures become reference sections, not\n"
     "   contract text.\n"
     "2. Append an `update` line to log.jsonl saying what changed and why.\n"
     "3. Confirm in one sentence. The change takes effect next skill load; note\n"
     "   that if it matters.\n"
     "\n"
     "Never weaken the hard rules (workers don't orchestrate, dispatch instead of\n"
     "implementing, TTS-sized replies) without the user saying so explicitly.\n"
    },
    {"routing.json",
     "{\n"
     "  \"classes\": {\n"
     "    \"planning\":  [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                  {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "    \"diagnosis\": [{\"backend\": \"codex\", \"model\": \"astra\"},\n"
     "                  {\"backend\": \"claude\", \"model\": \"fable\"}],\n"
     "    \"impl\":      [{\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "                  {\"backend\": \"grok\", \"model\": \"grok-4.6\"},\n"
     "                  {\"backend\": \"codex\", \"model\": \"sol\"}]\n"
     "  },\n"
     "  \"orchestrator\": {\"backend\": \"claude\", \"model\": \"opus[1m]\"},\n"
     "  \"seed_cost\": {\"planning\": 3, \"diagnosis\": 2, \"impl\": 5},\n"
     "  \"budgets\": {}\n"
     "}\n"
    },
};

const int orch_files_n = 11;
